opensearch-project/security-analytics

src/main/java/org/opensearch/securityanalytics/model/Detector.java
src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java

Populate data sources in detect and use in monitor under create detector flow.

Populate data sources in detect and use in monitor creation

---

src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
src/main/java/org/opensearch/securityanalytics/action/DeleteDetectorAction.java
src/main/java/org/opensearch/securityanalytics/action/DeleteDetectorRequest.java
src/main/java/org/opensearch/securityanalytics/action/DeleteDetectorResponse.java
src/main/java/org/opensearch/securityanalytics/model/Detector.java
src/main/java/org/opensearch/securityanalytics/resthandler/RestDeleteDetectorAction.java
src/main/java/org/opensearch/securityanalytics/resthandler/RestIndexDetectorAction.java
src/main/java/org/opensearch/securityanalytics/rules/objects/SigmaRule.java
src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java
src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
src/main/java/org/opensearch/securityanalytics/util/RuleTopicIndices.java
src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
src/test/java/org/opensearch/securityanalytics/TestHelpers.java
src/test/java/org/opensearch/securityanalytics/mapper/MapperIT.java
src/test/java/org/opensearch/securityanalytics/model/XContentTests.java
src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
src/test/java/org/opensearch/securityanalytics/rules/modifiers/SigmaCompareModifierTests.java
src/test/java/org/opensearch/securityanalytics/rules/modifiers/SigmaModifierTests.java
src/test/java/org/opensearch/securityanalytics/rules/objects/SigmaDetectionsTests.java
src/test/java/org/opensearch/securityanalytics/rules/objects/SigmaRuleTests.java

adds delete detector flow

---

src/main/java/org/opensearch/securityanalytics/action/IndexDetectorResponse.java
src/main/java/org/opensearch/securityanalytics/model/Detector.java
src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java
src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
src/test/java/org/opensearch/securityanalytics/TestHelpers.java
src/test/java/org/opensearch/securityanalytics/action/IndexDetectorResponseTests.java
src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java

adds support for list of monitors in detector

---

src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
src/main/java/org/opensearch/securityanalytics/action/CreateIndexMappingsRequest.java
src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java
src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
src/main/resources/OSMapping/windows/mappings.json
src/test/java/org/opensearch/securityanalytics/TestHelpers.java
src/test/java/org/opensearch/securityanalytics/findings/FindingIT.java
src/test/java/org/opensearch/securityanalytics/mapper/MapperIT.java

fix bug to support aliasMappings in create mappings api

fix bug to support aliasMappings in create mappings api

---

src/main/java/org/opensearch/securityanalytics/alerts/AlertsService.java
src/main/java/org/opensearch/securityanalytics/config/monitors/DetectorMonitorConfig.java
src/main/java/org/opensearch/securityanalytics/model/Detector.java
src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
src/test/java/org/opensearch/securityanalytics/TestHelpers.java
src/test/java/org/opensearch/securityanalytics/action/IndexDetectorResponseTests.java
src/test/java/org/opensearch/securityanalytics/alerts/AlertingServiceTests.java
src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
src/test/java/org/opensearch/securityanalytics/findings/FindingServiceTests.java

Added alert index history and pattern and findings index pattern to detector

new datasources fields to detector

---

src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java
src/main/resources/rules/windows/builtin/system/win_sample_rule.yml
src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
src/test/java/org/opensearch/securityanalytics/resthandler/RuleRestApiIT.java

fix for multi-node test faiures on rule ingestion

---

.github/workflows/ci.yml
src/main/resources/OSMapping/windows/fieldmappings.yml
src/main/resources/OSMapping/windows/mappings.json

add support for windows build

---

build.gradle

change groupid to publish at right location

change groupid to publish at right location

---

src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java

fix build for delete detector api

fix build for delete detector api

---

src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java

 update index monitor method to include namedWriteableRegistry for common utils interface 

---

src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
src/test/java/org/opensearch/securityanalytics/alerts/AlertingServiceTests.java

add owner field in monitor

---

.github/workflows/delete_backport_branch.yml

automate delete backport branch

automate delete backport branch

---

release-notes/opensearch-security-analytics.release-notes-2.4.0.0.md

Add 2.4.0.0 releases notes

---

src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java

Enabled findings in bucket level monitor creation

---

src/main/resources/OSMapping/linux/fieldmappings.yml
src/main/resources/OSMapping/linux/mappings.json
src/main/resources/OSMapping/network/fieldmappings.yml
src/main/resources/OSMapping/network/mappings.json
src/main/resources/OSMapping/windows/mappings.json

This PR adds self referential mappings as suggested by Subho for windows, linux, network (including firewall)
Missing mappings

add loopback mappings

---

src/main/java/org/opensearch/securityanalytics/transport/TransportAcknowledgeAlertsAction.java
src/main/java/org/opensearch/securityanalytics/transport/TransportGetAlertsAction.java
src/test/java/org/opensearch/securityanalytics/alerts/SecureAlertsRestApiIT.java
src/test/java/org/opensearch/securityanalytics/findings/SecureFindingRestApiIT.java
src/test/java/org/opensearch/securityanalytics/resthandler/SecureDetectorRestApiIT.java

Also edge case Secure IT tests covering above and others
Signed-off-by: Raj Chakravarthi <raj@icedome.ca>
(https://github.com/opensearch-project/security-analytics/issues/142)

implement securetransportaction for get alerts and ack alerts 

---

src/main/resources/OSMapping/linux/fieldmappings.yml
src/main/resources/OSMapping/linux/mappings.json

update Linux mappings
update Linux mappings

update Linux mappings

---

src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java
src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteRuleAction.java
src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
src/test/java/org/opensearch/securityanalytics/resthandler/RuleRestApiIT.java

Service Returns Unhandled Error Response

[Pen test]Service Returns Unhandled Error Response

---

src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java

fix ci builds for security-analytics

fix ci builds for security-analytics

---

release-notes/opensearch-security-analytics.release-notes-2.5.0.0.md

Signed-off-by: AWSHurneyt <hurneyt@amazon.com>
Added 2.5 release notes.
https://github.com/opensearch-project/security-analytics/issues/230

Added 2.5 release notes.

---

src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java
src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteRuleAction.java
src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
src/test/java/org/opensearch/securityanalytics/resthandler/RuleRestApiIT.java

[Backport 2.x] Service Returns Unhandled Error Response (#248)

[Backport 2.x] Service Returns Unhandled Error Response (#248)

---

src/main/java/org/opensearch/securityanalytics/mapper/IndexTemplateManager.java
src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java
src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java

added resolving index template conflicts; Added returning passed indexName in GetIndexMappings API response, instead of resolved concrete index name

index template conflict resovle; GetIndexMappings API changes

---

CODEOWNERS
MAINTAINERS.md

Updated the MAINTAINERS doc.
Added the CODEOWNERS doc.
https://github.com/opensearch-project/security-analytics/issues/324

Baselined MAINTAINERS and CODEOWNERS docs.

---

src/main/resources/OSMapping/others_compliance/fieldmappings.yml
src/main/resources/OSMapping/others_compliance/mappings.json

update others_compliance mappings
update others_compliance mappings

update others_compliance mappings

---

src/main/resources/OSMapping/others_web/fieldmappings.yml
src/main/resources/OSMapping/others_web/mappings.json

update others_web mappings
update others_web mappings

update others_web mappings

---

src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java

fix for integ test failures in 2.6

fix for integ test failures in 2.6

---

src/main/resources/OSMapping/mapper_topics.json
src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java

fix for failure in syslogs mappings view api

---

release-notes/opensearch-security-analytics.release-notes-2.6.0.0.md
release-notes/opensearch-security-analytics.release-notes-2.7.0.0.md
release-notes/opensearch-security-analytics.release-notes-2.8.0.0.md

Added 2.8 release notes

---

src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java
src/main/java/org/opensearch/securityanalytics/transport/TransportSearchDetectorAction.java
src/main/java/org/opensearch/securityanalytics/util/DetectorUtils.java
src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java

Manually backported PRs #384, and #396.

[Backport 2.5] Manually backported PRs 384, and 396.

---

build.gradle

update 2.x to 2.9

---

release-notes/opensearch-security-analytics.release-notes-2.9.0.0.md

Added 2.9 release notes.
https://github.com/opensearch-project/security-analytics/issues/471

Added 2.9 release notes.

---

build.gradle

Use core OpenSearch version of commons-lang3 to resolve version conflicts
N/A

Use core OpenSearch version of commons-lang3

---

release-notes/opensearch-security-analytics.release-notes-2.10.0.0.md

Added 2.10.0 release notes.

---

src/main/java/org/opensearch/securityanalytics/correlation/index/mapper/LuceneFieldMapper.java

Updates lucene path for MAX_DIMENSIONS

updated lucene MAX_DIMENSIONS path

---

build.gradle

Upgrade 2.x to 2.11

---

release-notes/opensearch-security-analytics.release-notes-2.11.0.0.md

Added 2.11 release notes.
https://github.com/opensearch-project/security-analytics/issues/562

Added 2.11 release notes.

---

src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java

Working integ test for tif

---

Dockerfile

remove dockerfile

---

release-notes/opensearch-security-analytics.release-notes-2.11.1.0.md

Added release notes for 2.11.1

Added release notes for 2.11.1

---

src/test/java/org/opensearch/securityanalytics/findings/FindingIT.java

Ignore flaky test

---

.github/CODEOWNERS
MAINTAINERS.md

Added to CODEOWNERS and MAINTAINERS files

---

release-notes/opensearch-security-analytics.release-notes-2.11.1.0.md

update release notes for 2.11.1

update release notes for 2.11.1

---

src/test/java/org/opensearch/securityanalytics/TestHelpers.java
src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java

[2.11] Backports [#722] to 2.11 add test to verify null filter in sigma rules

[2.11] Backports [#722] to 2.11 add test to verify null filter in sigma rules

---

src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java
src/main/resources/rules/test_windows/win_sample_rule.yml
src/test/java/org/opensearch/securityanalytics/TestHelpers.java
src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java
src/test/java/org/opensearch/securityanalytics/rules/backend/QueryBackendTests.java

[Backport 2.11] #725 Sigma keywords field not handled correctly

---

src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java
src/main/resources/rules/test_windows/win_sample_rule.yml
src/test/java/org/opensearch/securityanalytics/TestHelpers.java
src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java
src/test/java/org/opensearch/securityanalytics/rules/backend/QueryBackendTests.java

Backports https://github.com/opensearch-project/security-analytics/pull/725 to 2.9-with-features

[Backport 2.9-with-features] #725 Sigma keywords field not handled correctly

---

src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
src/main/java/org/opensearch/securityanalytics/model/CorrelationQuery.java
src/main/java/org/opensearch/securityanalytics/model/CorrelationRule.java
src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
src/main/resources/mappings/finding_mapping.json
src/test/java/org/opensearch/securityanalytics/TestHelpers.java
src/test/java/org/opensearch/securityanalytics/correlation/CorrelationEngineRestApiIT.java
src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java
src/test/java/org/opensearch/securityanalytics/rules/aggregation/AggregationBackendTests.java

Backport #737 to 2-11-with-features

Backport #737 to 2-11-with-features

---

DEVELOPER_GUIDE.md

Adds an initial implementation of a dev guide modeled after the one in the alerting repo.
- [N/A] New functionality includes testing.
- [N/A] All tests pass
- [N/A] New functionality has javadoc added

Add developer guide

---

.github/CODEOWNERS
MAINTAINERS.md

[Backport 2.x] Added to CODEOWNERS and MAINTAINERS files (#726)

---

src/test/java/org/opensearch/securityanalytics/alerts/AlertingServiceTests.java

Updated alert creation following https://github.com/opensearch-project/common-utils/pull/584.

Refactored alert tests

---

src/main/java/org/opensearch/securityanalytics/indexmanagment/DetectorIndexManagementService.java

Backport https://github.com/opensearch-project/security-analytics/commit/e77a7d99d26ee71a4d5377bbf793d7ed16fbaf0e from https://github.com/opensearch-project/security-analytics/pull/203

[Backport 2.x] Reduce log level for informative message (#203)

---

release-notes/opensearch-security-analytics.release-notes-2.12.0.0.md

Created release notes for 2.12

Release notes for 2.12.0

---

.github/CODEOWNERS
MAINTAINERS.md

Add goyamegh as a maintainer
NA

Add goyamegh as a maintainer

---

.github/CODEOWNERS
MAINTAINERS.md

Add goyamegh as a maintainer (#868)

---

src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
src/main/java/org/opensearch/securityanalytics/correlation/VectorEmbeddingsEngine.java
src/main/java/org/opensearch/securityanalytics/logtype/LogTypeService.java
src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
src/main/java/org/opensearch/securityanalytics/util/CorrelationIndices.java

* Refactor invocation of Action listeners in correlations
* Close hanging tasks in correlations workflow
* Logging finding id and monitor id in error logs
---------
#880 

Refactor invocation of Action listeners in correlations (#880)

---

src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java
src/main/resources/rules/test_windows/win_sample_rule.yml
src/test/java/org/opensearch/securityanalytics/TestHelpers.java
src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java
src/test/java/org/opensearch/securityanalytics/rules/backend/QueryBackendTests.java

Backport https://github.com/opensearch-project/security-analytics/pull/725 to 2.10

[Backport 2.10] #725 Sigma keywords field not handled correctly

---

src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java
src/main/resources/rules/test_windows/win_sample_rule.yml
src/test/java/org/opensearch/securityanalytics/TestHelpers.java
src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java
src/test/java/org/opensearch/securityanalytics/rules/backend/QueryBackendTests.java

Backport https://github.com/opensearch-project/security-analytics/pull/725 to 2.5

[Backport 2.5] #725 Sigma keywords field not handled correctly

---

build.gradle

Bumped 2.x to 2.13

---

build.gradle

Version bump to 2.7.1

---

release-notes/opensearch-security-analytics.release-notes-2.13.0.0.md

Added Release notes for 2.13.0

adding release notes for 2.13.0

---

release-notes/opensearch-security-analytics.release-notes-2.13.0.0.md

* adding release notes for 2.13.0
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* adding release notes for 2.13.0 PR
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* update release notes 2.13
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
---------
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
Signed-off-by: Riya <69919272+riysaxen-amzn@users.noreply.github.com>
(cherry picked from commit d82094d9eb17ddcace7a56a56d62e5c467e36632)
Backport PR for update in release notes [PR](https://github.com/opensearch-project/security-analytics/pull/946)
For more information on following Developer Certificate of Origin and signing off your …

Update the release notes 2.13 (#946)

---

src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java

[Backport 2.5] Fix keywords bug incorrectly adding field value (#964)

---

src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java

Manual backport of https://github.com/opensearch-project/security-analytics/pull/964

[Backport 2.11] Fix keywords bug incorrectly adding field value (#964)

---

src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java
src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteCorrelationRuleAction.java
src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteRuleAction.java
src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java

Added immediate refresh when deleting detector and correlation rules

Delete refresh fix

---

.github/ISSUE_TEMPLATE/office_hours.md

Template for users to create an issue/topic of discussion for office hours.
- [x ] Commits are signed per the DCO using --signoff 

Office hours template

---

build.gradle

Update 2.x to 2.14.0

---

.github/workflows/ci.yml
README.md
build-tools/opensearchplugin-coverage.gradle
build.gradle
src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java

improves code coverage to 80% by including coverage from integration tests.

fix code coverage calculation

---

.github/workflows/ci.yml
README.md
build-tools/opensearchplugin-coverage.gradle
build.gradle
src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java

backports #980 
- [] New functionality has javadoc added

[Backport 2.x] fix code coverage calculation

---

src/main/java/org/opensearch/securityanalytics/resthandler/RestGetAlertsAction.java
src/main/java/org/opensearch/securityanalytics/resthandler/RestGetFindingsAction.java

change default filter to time based fields

---

src/main/java/org/opensearch/securityanalytics/resthandler/RestGetAlertsAction.java
src/main/java/org/opensearch/securityanalytics/resthandler/RestGetFindingsAction.java

change default filter to time based fields (#1030) (#1033)

---

build.gradle
src/main/java/org/opensearch/securityanalytics/alerts/AlertsService.java

Update 2.x to 2.15.0
https://github.com/opensearch-project/opensearch-build/issues/4681

Update 2.x to 2.15.0

---

release-notes/opensearch-security-analytics.release-notes-2.15.0.0.md

Add 2.15 release notes

---

src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
src/main/java/org/opensearch/securityanalytics/jobscheduler/SecurityAnalyticsRunner.java
src/main/java/org/opensearch/securityanalytics/threatIntel/action/SAIndexTIFSourceConfigRequest.java
src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
src/main/java/org/opensearch/securityanalytics/threatIntel/resthandler/RestIndexTIFSourceConfigAction.java
src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigService.java
src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportGetTIFSourceConfigAction.java
src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportIndexTIFSourceConfigAction.java
src/test/java/org/opensearch/securityanalytics/action/IndexTIFSourceConfigRequestTests.java
src/test/java/org/opensearch/securityanalytics/resthandler/SATIFSourceConfigRestApiIT.java

This PR adds the skeleton for the job scheduler as well as some outline for integrating with IOC creation. It also adds in the delete and update functions that will be used for the APIs.

TIF Job Scheduler Initial Implementation

---

src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
src/main/java/org/opensearch/securityanalytics/correlation/alert/CorrelationAlertService.java
src/main/java/org/opensearch/securityanalytics/correlation/alert/CorrelationAlertsList.java
src/main/java/org/opensearch/securityanalytics/correlation/alert/CorrelationRuleScheduler.java
src/main/java/org/opensearch/securityanalytics/correlation/alert/notifications/CorrelationAlertContext.java
src/main/java/org/opensearch/securityanalytics/correlation/alert/notifications/NotificationService.java
src/main/java/org/opensearch/securityanalytics/model/CorrelationRule.java
src/main/java/org/opensearch/securityanalytics/model/CorrelationRuleTrigger.java
src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
src/main/java/org/opensearch/securityanalytics/util/CorrelationIndices.java
src/main/java/org/opensearch/securityanalytics/util/IndexUtils.java
src/main/resources/mappings/correlation_alert_mapping.json
src/test/java/org/opensearch/securityanalytics/TestHelpers.java
src/test/java/org/opensearch/securityanalytics/correlation/CorrelationEngineRestApiIT.java

Manual Backport PR
* notification for alerting in correlation
* correlation alerts mapping change
* working code
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* alertsInCorrelation without notifciations
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* alertsInCorrelation without notifciations
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* alertsInCorrelation without notifciations
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* alerts in correlations notification service added
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* addressing the comments
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* addressing the comments
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* address the design changes discussed
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* address the …

Alerts in correlations [Experminental] (#1040)

---

release-notes/opensearch-security-analytics.release-notes-2.15.0.0.md

* Updated the Release Notes with Correlation Alerts Feature

Updated the 2.15 release notes

---

src/main/java/org/opensearch/securityanalytics/action/GetAlertsRequest.java
src/main/java/org/opensearch/securityanalytics/alerts/AlertsService.java
src/main/java/org/opensearch/securityanalytics/resthandler/RestGetAlertsAction.java
src/main/java/org/opensearch/securityanalytics/transport/TransportAcknowledgeAlertsAction.java
src/main/java/org/opensearch/securityanalytics/transport/TransportGetAlertsAction.java
src/test/java/org/opensearch/securityanalytics/alerts/AlertingServiceTests.java
src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java

changes to add start_time and end_time filters to GetAlertsRequest

[2.15] Changes to add start_time and end_time filters to GetAlertsRequest 

---

src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
src/test/java/org/opensearch/securityanalytics/alerts/SecureAlertsRestApiIT.java
src/test/java/org/opensearch/securityanalytics/findings/FindingIT.java
src/test/java/org/opensearch/securityanalytics/findings/SecureFindingRestApiIT.java
src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java

pass integ tests

---

src/main/java/org/opensearch/securityanalytics/threatIntel/action/SAGetTIFSourceConfigResponse.java
src/main/java/org/opensearch/securityanalytics/threatIntel/action/SAIndexTIFSourceConfigResponse.java
src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java

Fix compile error

---

src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFSourceConfig.java
src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFSourceConfigDto.java
src/main/java/org/opensearch/securityanalytics/threatIntel/sacommons/TIFSourceConfig.java
src/main/java/org/opensearch/securityanalytics/threatIntel/sacommons/TIFSourceConfigDto.java
src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigService.java
src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportIndexTIFSourceConfigAction.java
src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportRefreshTIFSourceConfigAction.java
src/main/resources/mappings/threat_intel_job_mapping.json
src/test/java/org/opensearch/securityanalytics/TestHelpers.java
src/test/java/org/opensearch/securityanalytics/action/GetTIFSourceConfigResponseTests.java
src/test/java/org/opensearch/securityanalytics/action/IndexTIFSourceConfigResponseTests.java
src/test/java/org/opensearch/securityanalytics/model/SATIFSourceConfigDtoTests.java
src/test/java/org/opensearch/securityanalytics/model/SATIFSourceConfigTests.java
src/test/java/org/opensearch/securityanalytics/resthandler/SATIFSourceConfigRestApiIT.java

Fix mapping and add job parser todo

---

src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
src/main/java/org/opensearch/securityanalytics/action/TestS3ConnectionAction.java
src/main/java/org/opensearch/securityanalytics/action/TestS3ConnectionRequest.java
src/main/java/org/opensearch/securityanalytics/action/TestS3ConnectionResponse.java
src/main/java/org/opensearch/securityanalytics/resthandler/RestListIOCsAction.java
src/main/java/org/opensearch/securityanalytics/resthandler/RestTestS3ConnectionAction.java
src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java
src/main/java/org/opensearch/securityanalytics/transport/TransportTestS3ConnectionAction.java
src/main/plugin-metadata/plugin-security.policy
src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
src/test/java/org/opensearch/securityanalytics/resthandler/SATIFSourceConfigRestApiIT.java
src/test/java/org/opensearch/securityanalytics/resthandler/TestS3ConnectionRestIT.java
src/test/java/org/opensearch/securityanalytics/util/STIX2IOCGenerator.java

Implemented API to test s3 connection.
This PR is dependent on PR https://github.com/opensearch-project/security-analytics-commons/pull/11

Implemented API to test s3 connection.

---

src/main/resources/mappings/threat_intel_job_mapping.json

Fix user mapping in source config

---

src/main/java/org/opensearch/securityanalytics/action/ListIOCsActionRequest.java
src/main/java/org/opensearch/securityanalytics/model/STIX2IOC.java
src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java
src/main/java/org/opensearch/securityanalytics/resthandler/RestListIOCsAction.java
src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFeedStore.java
src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java
src/main/resources/mappings/stix2_ioc_mapping.json
src/test/java/org/opensearch/securityanalytics/resthandler/ListIOCsRestApiIT.java
src/test/java/org/opensearch/securityanalytics/util/STIX2IOCGenerator.java

Changes  list ioc params for consitency with other params

List Ioc Api params change

---

src/main/java/org/opensearch/securityanalytics/threatIntel/sacommons/monitor/ThreatIntelMonitorDto.java
src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportSearchThreatIntelMonitorAction.java
src/main/java/org/opensearch/securityanalytics/threatIntel/util/ThreatIntelMonitorUtils.java

fix search monitor to return dto and not model

---

src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportIndexThreatIntelMonitorAction.java
src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java

add guard rail for only one threat intel monitor to exist

---

src/main/java/org/opensearch/securityanalytics/action/ListIOCsAction.java
src/main/java/org/opensearch/securityanalytics/threatIntel/action/GetIocFindingsAction.java
src/main/java/org/opensearch/securityanalytics/threatIntel/action/PutTIFJobAction.java
src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/service/ThreatIntelMonitorRunner.java
src/main/java/org/opensearch/securityanalytics/threatIntel/sacommons/IndexTIFSourceConfigAction.java
src/main/java/org/opensearch/securityanalytics/threatIntel/sacommons/monitor/ThreatIntelMonitorActions.java

Fix API action names

---

src/main/java/org/opensearch/securityanalytics/action/ListIOCsActionRequest.java
src/main/java/org/opensearch/securityanalytics/resthandler/RestListIOCsAction.java
src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java
src/test/java/org/opensearch/securityanalytics/resthandler/ListIOCsRestApiIT.java
src/test/java/org/opensearch/securityanalytics/resthandler/SourceConfigWithoutS3RestApiIT.java
src/test/java/org/opensearch/securityanalytics/util/STIX2IOCGenerator.java

list iocs api. fix

---

src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFSourceConfigDto.java

Fix validation for source types

---

src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java

Create the iocs and check the validation before indexing source config

---

src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportIndexThreatIntelMonitorAction.java
src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java

fix update threat intel monitor to avoid monitor exists check before operation

---

src/main/java/org/opensearch/securityanalytics/threatIntel/action/SAIndexTIFSourceConfigRequest.java
src/main/java/org/opensearch/securityanalytics/threatIntel/common/SourceConfigDtoValidator.java
src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFSourceConfigDto.java

Add an action request validator for source config

---

src/main/resources/mappings/threat_intel_job_mapping.json

fix mapping

---

src/main/java/org/opensearch/securityanalytics/model/threatintel/IocWithFeeds.java

Feed name fix

---

src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java

Fixed `ThreatIntelMonitorRestApiIT` test following enum changes.

Fixed test case.

---

src/test/java/org/opensearch/securityanalytics/correlation/alerts/CorrelationAlertsRestApiIT.java

Fix 2.x compile errors

---

src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java
src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java

Refactored ListIOCs API to return the correct number of findings for each IOC.

ListIOCs API to return number of findings per IOC.

---

src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFeedStore.java
src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java
src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigService.java
src/test/java/org/opensearch/securityanalytics/resthandler/SourceConfigWithoutS3RestApiIT.java

Cleans up the store config when new ioc types gets updated. Also adds integ tests for ioc upload source config

Ioc upload integ tests and fix update

---

src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/dto/IocScanContext.java
src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/service/IoCScanService.java
src/main/java/org/opensearch/securityanalytics/threatIntel/model/monitor/TransportThreatIntelMonitorFanOutAction.java
src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigService.java
src/main/java/org/opensearch/securityanalytics/util/IndexUtils.java
src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java

Backports #1173 and #1178 to 2.x 

---

src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFeedStore.java
src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java

1. Fixed bulk indexing for IOCs.
2. Added additional logs.

Fixed bulk indexing for IOCs.

---

release-notes/opensearch-security-analytics.release-notes-2.16.0.0.md

Added 2.16 Release Notes

---

build.gradle

Incremented version to 2.16.0.

---

src/main/java/org/opensearch/securityanalytics/action/GetAlertsRequest.java
src/main/java/org/opensearch/securityanalytics/alerts/AlertsService.java
src/main/java/org/opensearch/securityanalytics/resthandler/RestGetAlertsAction.java
src/main/java/org/opensearch/securityanalytics/transport/TransportAcknowledgeAlertsAction.java
src/main/java/org/opensearch/securityanalytics/transport/TransportGetAlertsAction.java
src/test/java/org/opensearch/securityanalytics/alerts/AlertingServiceTests.java
src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java

…1039)
Backporting changes to GetAlertsRequest to 2.13

[Backport 2.13] changes to add start_time and end_time filters to GetAlertsRequest (#1039)

---

release-notes/opensearch-security-analytics.release-notes-2.16.0.0.md
src/main/java/org/opensearch/securityanalytics/model/STIX2IOC.java
src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java
src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java
src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/dto/PerIocTypeScanInputDto.java
src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFSourceConfigDto.java
src/main/java/org/opensearch/securityanalytics/threatIntel/model/monitor/PerIocTypeScanInput.java
src/main/java/org/opensearch/securityanalytics/threatIntel/model/monitor/ThreatIntelTrigger.java
src/main/java/org/opensearch/securityanalytics/threatIntel/resthandler/monitor/RestIndexThreatIntelMonitorAction.java
src/main/java/org/opensearch/securityanalytics/threatIntel/resthandler/monitor/RestUpdateThreatIntelAlertsStatusAction.java
src/main/java/org/opensearch/securityanalytics/threatIntel/sacommons/monitor/ThreatIntelTriggerDto.java
src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportIndexThreatIntelMonitorAction.java
src/test/java/org/opensearch/securityanalytics/model/STIX2IOCDtoTests.java
src/test/java/org/opensearch/securityanalytics/model/STIX2IOCTests.java
src/test/java/org/opensearch/securityanalytics/resthandler/SATIFSourceConfigRestApiIT.java
src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java
src/test/java/org/opensearch/securityanalytics/util/STIX2IOCGenerator.java

1. Added logic to catch more exceptions, and wrap more exceptions.
2. Updated jar to reflect changes in PR https://github.com/opensearch-project/security-analytics-commons/pull/19

Catch and wrap exceptions.

---

release-notes/opensearch-security-analytics.release-notes-2.16.0.0.md
src/main/java/org/opensearch/securityanalytics/model/STIX2IOC.java
src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java
src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java
src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/dto/PerIocTypeScanInputDto.java
src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFSourceConfigDto.java
src/main/java/org/opensearch/securityanalytics/threatIntel/model/monitor/PerIocTypeScanInput.java
src/main/java/org/opensearch/securityanalytics/threatIntel/model/monitor/ThreatIntelTrigger.java
src/main/java/org/opensearch/securityanalytics/threatIntel/resthandler/monitor/RestIndexThreatIntelMonitorAction.java
src/main/java/org/opensearch/securityanalytics/threatIntel/resthandler/monitor/RestUpdateThreatIntelAlertsStatusAction.java
src/main/java/org/opensearch/securityanalytics/threatIntel/sacommons/monitor/ThreatIntelTriggerDto.java
src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportIndexThreatIntelMonitorAction.java
src/test/java/org/opensearch/securityanalytics/model/STIX2IOCDtoTests.java
src/test/java/org/opensearch/securityanalytics/model/STIX2IOCTests.java
src/test/java/org/opensearch/securityanalytics/resthandler/SATIFSourceConfigRestApiIT.java
src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java
src/test/java/org/opensearch/securityanalytics/util/STIX2IOCGenerator.java

[Backport 2.x] Catch and wrap exceptions. #1198

---

src/main/java/org/opensearch/securityanalytics/model/STIX2IOC.java
src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java
src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java
src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/dto/PerIocTypeScanInputDto.java
src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFSourceConfigDto.java
src/main/java/org/opensearch/securityanalytics/threatIntel/model/monitor/PerIocTypeScanInput.java
src/main/java/org/opensearch/securityanalytics/threatIntel/model/monitor/ThreatIntelTrigger.java
src/main/java/org/opensearch/securityanalytics/threatIntel/resthandler/monitor/RestIndexThreatIntelMonitorAction.java
src/main/java/org/opensearch/securityanalytics/threatIntel/resthandler/monitor/RestUpdateThreatIntelAlertsStatusAction.java
src/main/java/org/opensearch/securityanalytics/threatIntel/sacommons/monitor/ThreatIntelTriggerDto.java
src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportIndexThreatIntelMonitorAction.java
src/test/java/org/opensearch/securityanalytics/model/STIX2IOCDtoTests.java
src/test/java/org/opensearch/securityanalytics/model/STIX2IOCTests.java
src/test/java/org/opensearch/securityanalytics/resthandler/SATIFSourceConfigRestApiIT.java
src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java
src/test/java/org/opensearch/securityanalytics/util/STIX2IOCGenerator.java

Manual backport of PR https://github.com/opensearch-project/security-analytics/pull/1198

[Backport 2.15] Catch and wrap exceptions. (#1198)

---

src/main/java/org/opensearch/securityanalytics/action/GetDetectorResponse.java

This Pr adds a trigger field in GetDetectorsAPI response
* Fixes the issue where SA crashes, when a user tries to create Alert in Detector Details Page while viewing Findings
API response for:
http://localhost:9200/_plugins/_security_analytics/detectors/akpmM5EB3Y4wm-vZ4JFZ
```
{
"_id": "akpmM5EB3Y4wm-vZ4JFZ",
"_version": 1,
"detector": {
"name": "detector1",
"detector_type": "ad_ldap",
"enabled": true,
"schedule": {
"period": {
"interval": 1,
"unit": "MINUTES"
}
},
"inputs": [
{
"detector_input": {
"description": "",
"indices": [
"my-index-000001"
],
"custom_rules": [
{
"id": "WUpmM5EB3Y4wm-vZgJE9"
}
],
"pre_packaged_rules": []
}
}
],
"last_update_time": "2024-08-08T19:10:59.741Z",
"enabled_time": "2024-08-08T19:10:59.738Z",
"threat_intel_enabled": true,
"triggers": [
{
"id": …
```

added triggers in getDetectors API response

---

src/main/java/org/opensearch/securityanalytics/threatIntel/common/TIFLockService.java
src/main/java/org/opensearch/securityanalytics/threatIntel/service/DefaultTifSourceConfigLoaderService.java
src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigService.java
src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportGetIocFindingsAction.java
src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportIndexTIFSourceConfigAction.java
src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportGetThreatIntelAlertsAction.java
src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportUpdateThreatIntelAlertStatusAction.java
src/test/java/org/opensearch/securityanalytics/resthandler/SourceConfigWithoutS3RestApiIT.java
src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java
src/test/java/org/opensearch/securityanalytics/threatIntel/common/ThreatIntelLockServiceTests.java

This PR contains bug fixes that were found for threat intel:
- Fixes the initial creation for the default source config so that it catches an index not found exception.
- fixes the number of conditions created from a match query
- Fixes threat intel source update when trying to deactivate and activate

Bug fixes for threat intel

---

src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportGetThreatIntelAlertsAction.java
src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportIndexThreatIntelMonitorAction.java
src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java

[Backport 2.15] Backport #1234 to 2.15

---

src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportGetThreatIntelAlertsAction.java
src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportIndexThreatIntelMonitorAction.java
src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java

[Backport 2.x] Backport #1234 to 2.x

---

src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportGetThreatIntelAlertsAction.java
src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportIndexThreatIntelMonitorAction.java
src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java

[Backport 2.16] Backport #1234 to 2.16

---

src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/service/SaIoCScanService.java
src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java
src/main/resources/mappings/stix2_ioc_mapping.json
src/test/java/org/opensearch/securityanalytics/resthandler/ListIOCsRestApiIT.java
src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java

Fixed searchString bug. Removed nested IOC mapping structure.

Fixed searchString bug. Removed nested IOC mapping structure.

---

build.gradle

Incremented version to 2.17.0.
Resolves https://github.com/opensearch-project/security-analytics/issues/1216

Incremented version to 2.17.0.

---

release-notes/opensearch-security-analytics.release-notes-2.17.0.0.md

Added 2.17.0 release notes

---

src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
src/main/java/org/opensearch/securityanalytics/transport/TransportAckCorrelationAlertsAction.java
src/main/java/org/opensearch/securityanalytics/transport/TransportGetCorrelationAlertsAction.java

* Added stash context for getCorrelationAlerts and ackCorrelationAlerts api since `.opensearch-sap-correlation-alerts` is a system index
* Added CorrelationAlert Index to System Index descriptor
[Resolves #[Issue number to be closed when this PR is merged]](https://github.com/opensearch-project/security-analytics/issues/988)

Stashcontext sa

---

.github/workflows/ci.yml
.github/workflows/multi-node-test-workflow.yml

CIs would fail due to outdated artifact error. Upgrading artfiacts to resolve.

upgrade upload artifacts

---

build.gradle

Incremented version to 2.18.0

---

.github/workflows/ci.yml
.github/workflows/multi-node-test-workflow.yml
src/main/java/org/opensearch/securityanalytics/logtype/BuiltinLogTypeLoader.java

remove redundant logic to fix OS launch exception
Resolves #1273 

remove redundant logic to fix OS launch exception and updates actions/upload-artifac2 to @V3

---

release-notes/opensearch-security-analytics.release-notes-2.17.1.0.md

add release notes for 2.17.1

---

src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java

update min number of replicas to 0
manual backport of #1364 

update min number of replicas to 0

---

release-notes/opensearch-security-analytics.release-notes-2.18.0.0.md

Added 2.18.0 release notes.
https://github.com/opensearch-project/security-analytics/issues/1295

Added 2.18 release notes.

---

src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java

Replaces hard-coded password in integration test with randomly generated string for security purposes
- [Y] New functionality includes testing.
- [N/A] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [Y] Commits are signed per the DCO using `--signoff`.
- [N/A] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).
For more information on following Developer Certificate of Origin and signing off your commits, please check …

Replacing hard-coded password with randomly generated string

---

.github/workflows/ci.yml
build.gradle

Bumping 2.x branch version to 2.19.0 to resolve CI failures in PRs to 2.x branch.

bumping version to 2.19.0

---

.github/workflows/multi-node-test-workflow.yml

CVE details:
```
{
"VulnerabilityID": "CVE-2024-47535",
"PkgName": "io.netty:netty-common",
"PkgPath": "usr/share/opensearch/plugins/opensearch-security-analytics/security-analytics-commons-1.0.0.jar",
"PkgIdentifier": {
"PURL": "pkg:maven/io.netty/netty-common@4.1.108.Final"
},
"InstalledVersion": "4.1.108.Final",
"FixedVersion": "4.1.115",
"Status": "fixed",
"Layer": {
"Digest": "sha256:490d0de45822d74701c986814b57e4d8132164424019877b38915dadc07ae80a",
"DiffID": "sha256:1d1542b17eec3a37159135e2fce5b242073af921fcdbdd889b267c28ace4e2a4"
},
"SeveritySource": "ghsa",
"PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-47535",
"DataSource": {
"ID": "ghsa",
"Name": "GitHub Security Advisory Maven",
"URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven"
},
"Title": …
```

Fix CVE-2024-47535.

---

build.gradle

Incremented version to 2.19.1.

Incremented version to 2.19.1.

---

release-notes/opensearch-security-analytics.release-notes-2.19.1.0.md

Added 2.19.1 release notes.

---

build.gradle

Update version qualifier to beta1.
https://github.com/opensearch-project/security-analytics/issues/1025

Update version qualifier to beta1.

---

release-notes/opensearch-security-analytics.release-notes-3.0.0.0-beta1.md

Added 3.0-beta1 release notes.
https://github.com/opensearch-project/security-analytics/issues/1025

Added 3.0-beta1 release notes.

---

build.gradle

Adds updateVersion task in build.gradle to automate version bumps.

Add updateVersion task

---

release-notes/opensearch-security-analytics.release-notes-3.0.0.0.md

* Added release notes for SA 3.0

added release notes for 3.0

---

release-notes/opensearch-security-analytics.release-notes-3.1.0.0.md

- added release notes for SA 3.1 

added release notes for 3.1

---

build.gradle
src/test/java/org/opensearch/securityanalytics/TestHelpers.java
src/test/java/org/opensearch/securityanalytics/model/WriteableTests.java
src/test/java/org/opensearch/securityanalytics/model/XContentTests.java

Increment version to 3.3.0-SNAPSHOT
This contains a commit to adapt to the changes from https://github.com/opensearch-project/common-utils/pull/827

Increment version to 3.3.0-SNAPSHOT
