src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java, src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteRuleAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexRuleAction.java, src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java, src/test/java/org/opensearch/securityanalytics/findings/FindingIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/RuleRestApiIT.java
Rule can be created when no detector exist in the system, or some detectors exist in the system.
A Rule may be used or not used by any detector.
this PR is created to handle the edge cases when a rule is created but not used by any detector. When we try to update/delete the rule we face an error today.
=> fix bug on deleting/updating rule when it is not used by detectors

src/main/java/org/opensearch/securityanalytics/model/DetectorTrigger.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
add support for context variables in subject & message templates
=> add support for context variables in subject & message templates

scripts/build.sh
add build.sh to generate maven artifacts
=> add build.sh to generate maven artifacts

.github/workflows/backport.yml, build.gradle
=> add backport github workflow for security-analytics

src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
=> Add findings enabled flag in datasources

src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
Changes method to use update from https://github.com/opensearch-project/common-utils/pull/304
=> update index monitor method to include namedWriteableRegistry for common utils interface

src/main/java/org/opensearch/securityanalytics/action/FindingDto.java, src/test/java/org/opensearch/securityanalytics/findings/FindingDtoTests.java
findingsDto assign detectorId bug
=> findingsDto assign detectorId bug

src/main/java/org/opensearch/securityanalytics/findings/FindingsService.java
=> removed grouped listener when fetching findings

src/main/resources/OSMapping/cloudtrail/fieldmappings.yml, src/main/resources/OSMapping/cloudtrail/mappings.json, src/main/resources/OSMapping/dns/fieldmappings.yml, src/main/resources/OSMapping/dns/mappings.json, src/main/resources/OSMapping/s3/fieldmappings.yml, src/main/resources/OSMapping/s3/mappings.json, src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java, src/test/resources/cloudtrail-sample-s3.json, src/test/resources/cloudtrail-sample.json, src/test/resources/dns-sample.json
This PR adds DNS mappings, adds a test case to MappingsIT that reads the json file from resources and submits it via the API
Mapping curation, for DNS
- [ X] New functionality includes testing.
- [X ] All tests pass
=> add mappings and test case

src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
Signed-off-by: Stevan Buzejic <stevan.buzejic@htecgroup.com>
Enabled empty detector (detector without rules) creation.
Added response handling on detector create request when the list of rules is empty.
=> Enabled creation detector without rules

src/main/java/org/opensearch/securityanalytics/transport/TransportGetAlertsAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportGetFindingsAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportGetIndexMappingsAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportGetMappingsViewAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportUpdateIndexMappingsAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportValidateRulesAction.java, src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java, src/test/java/org/opensearch/securityanalytics/findings/FindingIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
=> added 404s

src/main/resources/rules/test_windows/dns_query_win_regsvr32_network_activity.yml, src/main/resources/rules/test_windows/net_connection_win_regsvr32_network_activity.yml, src/main/resources/rules/test_windows/proc_creation_win_susp_regsvr32_no_dll.yml, src/main/resources/rules/test_windows/proc_creation_win_system_exe_anomaly.yml, src/main/resources/rules/test_windows/win_sample_rule.yml
=> investigate integration test failures

release-notes/opensearch-security-analytics.release-notes-2.4.1.0.md
=> Add release notes for 2.4.1

.github/workflows/ci.yml, .github/workflows/multi-node-test-workflow.yml
add failure logs to github workflows
=> add failure logs to github workflows

src/main/java/org/opensearch/securityanalytics/rules/backend/QueryBackend.java, src/main/java/org/opensearch/securityanalytics/rules/objects/SigmaRule.java, src/test/java/org/opensearch/securityanalytics/rules/objects/SigmaDetectionsTests.java
fix vulnerabiity in yaml constructor
=> fix vulnerabiity in yaml constructor

src/main/java/org/opensearch/securityanalytics/mapper/MappingsTraverser.java, src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java, src/test/java/org/opensearch/securityanalytics/mapper/MapperUtilsTests.java
GetMappingsView API was returning aliases in "unmapped_index_fields" due to bug in field type filtering.
#171 
=> fixed aliases being returned in unmapped_index_fields

src/main/java/org/opensearch/securityanalytics/action/IndexRuleRequest.java, src/main/java/org/opensearch/securityanalytics/config/monitors/DetectorMonitorConfig.java, src/main/java/org/opensearch/securityanalytics/mapper/MapperTopicStore.java, src/main/java/org/opensearch/securityanalytics/model/Detector.java, src/main/java/org/opensearch/securityanalytics/model/DetectorTrigger.java, src/main/java/org/opensearch/securityanalytics/transport/TransportGetAlertsAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportGetFindingsAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexRuleAction.java, src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/RuleRestApiIT.java
Signed-off-by: Raj Chakravarthi <raj@icedome.ca>
After this change, the detector type will be returned in small case during search.
Also, integration tests are written to ensure that happens in create, update, get , search detector.
(https://github.com/opensearch-project/security-analytics/issues/173) 
=> search returns detector type in CAPS fix and integration tests

src/main/resources/OSMapping/ad_ldap/fieldmappings.yml, src/main/resources/OSMapping/ad_ldap/mappings.json
Signed-off-by: Grant Haywood <grant@phaseshift.studio>
updated ad_ldap mappings
updated ad_ldap mappings
=> updated ad_ldap mappings

src/main/resources/OSMapping/network/fieldmappings.yml, src/main/resources/OSMapping/network/mappings.json
Signed-off-by: Grant Haywood <grant@phaseshift.studio>
updated network mappings
updated network mappings
=> updated network mappings

src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java, src/test/java/org/opensearch/securityanalytics/alerts/SecureAlertsRestApiIT.java, src/test/java/org/opensearch/securityanalytics/findings/SecureFindingRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/SecureDetectorRestApiIT.java
Checks if user can access the given indices when creating detector
Implemented approach 2 from the issue listed below. Introduced dummy index search before detector creation happens, since once the detector is being created the context is stashed and from that point, the program continues the execution as a super user (which has an access to resources on altering and security analytics side). 
That's why, the check has been introduced before the context is being stashed and follows the approach used in alerting.
One general note - security tests will fail because the index privilege action is not introduced for the security_analytics_full_access role
https://github.com/opensearch-project/security-analytics/issues/1 …
=> Added dummy search when creating detector on the given indicies

src/test/java/org/opensearch/securityanalytics/findings/SecureFindingRestApiIT.java
Signed-off-by: Stevan Buzejic <buzejic.stevan@gmail.com>
Fix for SecureFindingRestApiIT -> removed upperCasing without specified locale
https://github.com/opensearch-project/security-analytics/issues/246
=> Fixed SecureFindingRestApiIT. Removed uppercasing of the detector type

src/main/resources/OSMapping/cloudtrail/fieldmappings.yml, src/main/resources/OSMapping/linux/mappings.json, src/main/resources/rules/ad_ldap/azure_aad_secops_signin_failure_bad_password_threshold.yml, src/main/resources/rules/ad_ldap/azure_aadhybridhealth_adfs_new_server.yml, src/main/resources/rules/ad_ldap/azure_aadhybridhealth_adfs_service_delete.yml, src/main/resources/rules/ad_ldap/azure_ad_bitlocker_key_retrieval.yml, src/main/resources/rules/ad_ldap/azure_ad_device_registration_or_join_without_mfa.yml, src/main/resources/rules/ad_ldap/azure_ad_device_registration_policy_changes.yml, src/main/resources/rules/ad_ldap/azure_ad_sign_ins_from_noncompliant_devices.yml, src/main/resources/rules/ad_ldap/azure_ad_sign_ins_from_unknown_devices.yml, src/main/resources/rules/ad_ldap/azure_ad_user_added_to_admin_role.yml, src/main/resources/rules/ad_ldap/azure_ad_users_added_to_device_admin_roles.yml, src/main/resources/rules/ad_ldap/win_ldap_recon.yml, src/main/resources/rules/cloudtrail/aws_s3_data_management_tampering.yml, src/main/resources/rules/windows/builtin/system/win_sample_rule.yml
=> add mapping fixes

src/main/resources/OSMapping/linux/mappings.json
Fixes inconsistent Linux mapping found by mapping verification script
Fixes inconsistent Linux mapping found by mapping verification script
- [ X] All tests pass
=> correct linux mapping error

src/main/java/org/opensearch/securityanalytics/rules/objects/SigmaRule.java, src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsPluginTransportIT.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
add nesting level to yaml constructor
=> add nesting level to yaml constructor

src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java, src/main/java/org/opensearch/securityanalytics/mapper/MappingsTraverser.java, src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java, src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java, src/test/java/org/opensearch/securityanalytics/mapper/MappingsTraverserTests.java
bug fix regarding "timestamp" alias
=> GetIndexMapping API bugfix

src/main/java/org/opensearch/securityanalytics/util/SecurityAnalyticsException.java
log message change for debugging
=> log message change for debugging

src/main/resources/OSMapping/others_apt/fieldmappings.yml, src/main/resources/OSMapping/others_apt/mappings.json
update others_apt mappings
update others_apt mappings
=> update others_apt mappings

src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java, src/main/java/org/opensearch/securityanalytics/rules/backend/QueryBackend.java, src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java, src/main/resources/mappings/rules.json, src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java
Fixed query_field_names being accumulated when loading per-packgaged rules
=> query_field_names bugfix

src/main/resources/OSMapping/others_cloud/fieldmappings.yml, src/main/resources/OSMapping/others_cloud/mappings.json
update others_cloud mappings
update others_cloud mappings
=> update others_cloud mappings

build.gradle, src/main/java/org/opensearch/securityanalytics/action/GetIndexMappingsResponse.java, src/main/java/org/opensearch/securityanalytics/action/GetMappingsViewResponse.java, src/main/java/org/opensearch/securityanalytics/action/ValidateRulesResponse.java, src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
=> Bump to OpenSearch 2.6

.github/workflows/maven-publish.yml, build.gradle
Publish snapshots to maven via GHA
#334
```
find snapshots | sort
snapshots
snapshots/org
snapshots/org/opensearch
snapshots/org/opensearch/plugin
snapshots/org/opensearch/plugin/opensearch-security-analytics
snapshots/org/opensearch/plugin/opensearch-security-analytics/2.5.0.0-SNAPSHOT
snapshots/org/opensearch/plugin/opensearch-security-analytics/2.5.0.0-SNAPSHOT/maven-metadata.xml
snapshots/org/opensearch/plugin/opensearch-security-analytics/2.5.0.0-SNAPSHOT/maven-metadata.xml.md5
snapshots/org/opensearch/plugin/opensearch-security-analytics/2.5.0.0-SNAPSHOT/maven-metadata.xml.sha1
snapshots/org/opensearch/plugin/opensearch-security-analytics/2.5.0.0-SNAPSHOT/maven-metadata.xml.sha256
snapshots/org/opensearch/plugin/opensearch-security-analytics/2.5.0.0-SNAPSHOT/maven-metadata.xml.sha512 …
```
=> Publish snapshots to maven via GHA

release-notes/opensearch-security-analytics.release-notes-2.6.0.0.md
Drafted 2.6 release notes.
https://github.com/opensearch-project/security-analytics/issues/333
=> Drafted 2.6 release notes.

src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportSearchDetectorAction.java, src/main/java/org/opensearch/securityanalytics/util/DetectorUtils.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
Detector search api throws 404 when detector config index doesn't exist. this PR fixes that scenario to return a 0 hits search response.
Detector deletion API returns message that index is not found when index doesnt exist. Fixed it to return "detector not found" message.
#206 #370
=> Handle index not exists for detector search and delete

src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java, src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
Handle monitor or monitor index(`.opendistro-alerting-config`) not found during detector deletion to proceed with detector deletion. 
But if there are other errors thrown from monitor deletion then we log it and fail the request
#378 
=> Handle monitor or monitor index not found during detector deletion

src/main/resources/mappings/finding_mapping.json, src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java, src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java, src/test/java/org/opensearch/securityanalytics/findings/FindingIT.java
Added missing mappings changes in finding_mappings.json
=> Findings index mappings fix

src/main/java/org/opensearch/securityanalytics/resthandler/RestSearchRuleAction.java, src/test/java/org/opensearch/securityanalytics/resthandler/RuleRestApiIT.java
Enable source filtering capability on SearchRule API
#331
=> SearchRule API - source filtering

src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
Alias and dataStream end-to-end integration tests
=> Alias and dataStream end-to-end ITs

.github/CODEOWNERS, CODEOWNERS
Moved CODEOWNERS files to align with org requirements.
https://github.com/opensearch-project/security-analytics/issues/324
=> Moved CODEOWNERS files to align with org requirements.

src/main/java/org/opensearch/securityanalytics/action/CorrelatedFindingAction.java, src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java, src/main/java/org/opensearch/securityanalytics/correlation/VectorEmbeddingsEngine.java, src/main/java/org/opensearch/securityanalytics/model/CorrelatedFinding.java, src/main/java/org/opensearch/securityanalytics/model/FindingWithScore.java, src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportListCorrelationAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportSearchCorrelationAction.java, src/main/resources/mappings/correlation.json, src/test/java/org/opensearch/securityanalytics/correlation/CorrelationEngineRestApiIT.java
add rules to correlations for correlation engine
=> add rules to correlations for correlation engine

src/main/java/org/opensearch/securityanalytics/action/IndexCorrelationRuleRequest.java, src/main/java/org/opensearch/securityanalytics/model/CorrelationRule.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/correlation/CorrelationEngineRuleRestApiIT.java
fix for input validation of correlation rule names
=> fix for input validation of correlation rule names

src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java, src/test/java/org/opensearch/securityanalytics/alerts/SecureAlertsRestApiIT.java, src/test/java/org/opensearch/securityanalytics/findings/SecureFindingRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/SecureDetectorRestApiIT.java
This change is to accommodate security plugin change https://github.com/opensearch-project/security/pull/2784
=> Use strong password in security test

src/main/java/org/opensearch/securityanalytics/resthandler/RestIndexCorrelationRuleAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteCorrelationRuleAction.java, src/test/java/org/opensearch/securityanalytics/correlation/CorrelationEngineRuleRestApiIT.java
correlation rule search, delete and edit api
=> correlation rule search, delete and edit api

src/main/java/org/opensearch/securityanalytics/action/IndexCustomLogTypeRequest.java, src/main/java/org/opensearch/securityanalytics/logtype/LogTypeService.java, src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java, src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteCustomLogTypeAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexCustomLogTypeAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportListCorrelationAction.java, src/main/resources/mappings/log_type_config_mapping.json, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/resthandler/CustomLogTypeRestApiIT.java
fix for mappings of custom log types & other bug fixes
#447 
=> fix for mappings of custom log types & other bug fixes

build.gradle
Fix google-java-format-1.17.0.jar: 1 vulnerabilities
CVE: https://www.mend.io/vulnerability-database/CVE-2023-2976
=> [CVE-2023-2976] Fix google-java-format-1.17.0.jar: 1 vulnerabilities

.github/CODEOWNERS, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
Fixes detectors that have incompatible detector types with detector rules.
[#518](https://github.com/opensearch-project/security-analytics/issues/518)
=> Fixes detectorType incompatibility with detector rules

src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java, src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java, src/main/java/org/opensearch/securityanalytics/correlation/VectorEmbeddingsEngine.java, src/main/java/org/opensearch/securityanalytics/logtype/LogTypeService.java, src/main/java/org/opensearch/securityanalytics/resthandler/RestSearchCorrelationRuleAction.java, src/main/java/org/opensearch/securityanalytics/resthandler/RestSearchDetectorAction.java, src/main/java/org/opensearch/securityanalytics/resthandler/RestSearchRuleAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteRuleAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportGetAlertsAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportGetFindingsAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexRuleAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportListCorrelationAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportSearchCorrelationAction.java, src/main/java/org/opensearch/securityanalytics/util/DetectorUtils.java, src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java, src/main/java/org/opensearch/securityanalytics/util/RuleValidator.java
=> segment replication changes

build.gradle
Force google guava to 32.0.1 due to spotless still using 31.1
N/A
=> Force google guava to 32.0.1

build.gradle, src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java, src/main/java/org/opensearch/securityanalytics/model/Detector.java, src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java, src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportGetFindingsAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/main/java/org/opensearch/securityanalytics/util/MonitorService.java, src/main/java/org/opensearch/securityanalytics/util/WorkflowService.java, src/main/resources/mappings/detectors.json, src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/action/IndexDetectorResponseTests.java, src/test/java/org/opensearch/securityanalytics/alerts/AlertingServiceTests.java, src/test/java/org/opensearch/securityanalytics/findings/FindingServiceTests.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
Enables workflow creation - all the monitors related with the given detector will be part of the detector Enables workflow update during detector update
Deletes the workflow during the detector deletion
Adds additional field to a detector
=> Using alerting workflows in detectors  (#394)

build.gradle, src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java, src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java, src/main/java/org/opensearch/securityanalytics/util/AutoCorrelationsRepo.java, src/main/resources/correlations/mitre_correlation.json, src/test/java/org/opensearch/securityanalytics/correlation/CorrelationEngineRestApiIT.java
Findings in security-analytics link sigma rules to logs. Each sigma rule is linked to one or more mitre tactics & techniques. this info along with mitre cti relationships are used to generate auto-correlations among findings.
this pr add mitre attack based auto-correlations support in correlation engine. https://github.com/mitre/cti
=> add mitre attack based auto-correlations support in correlation engine

src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java, src/main/java/org/opensearch/securityanalytics/model/Detector.java, src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java, src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportGetFindingsAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/main/java/org/opensearch/securityanalytics/util/MonitorService.java, src/main/java/org/opensearch/securityanalytics/util/WorkflowService.java, src/main/resources/mappings/detectors.json, src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/action/IndexDetectorResponseTests.java, src/test/java/org/opensearch/securityanalytics/alerts/AlertingServiceTests.java, src/test/java/org/opensearch/securityanalytics/findings/FindingServiceTests.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
=> Using alerting workflows in detectors

src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java
Auto expand replicas so for single node clusters, it wouldn't try to create a replica and cause the cluster to be yellow
N/A
=> Auto expand replicas

src/main/java/org/opensearch/securityanalytics/model/DetectorTrigger.java, src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/main/java/org/opensearch/securityanalytics/util/DetectorUtils.java, src/main/java/org/opensearch/securityanalytics/util/WorkflowService.java, src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
- For each group by rule a bucket level monitor is created.
- Bucket level monitor doesn't support the current detector triggers which cater focussedly to per document alerting 
- This change uses workflow's chained monitor findings feature to feed findings generated by all bucket level monitors as source data to a match all doc level monitor. The chained findings monitor simply creates findings for all docs which match the bucket level monitor rule and honors the detector trigger condition creating alerts if there are any group by rules mentioned in the trigger.
Behaviour of non-group by rule matching is unaffected.
=> adds support for alerts and triggers on group by based sigma rules 

src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
Fixes 2.10.0 integ tests failures by retrieving the workflow search through a post API call.
[#525](https://github.com/opensearch-project/security-analytics/issues/525)
=> Fixes verifying workflow test when security is enabled

src/main/java/org/opensearch/securityanalytics/logtype/LogTypeService.java, src/main/java/org/opensearch/securityanalytics/util/CustomLogTypeIndices.java
auto expand replicas for logtype index
makes single-node OS cluster green
=> auto expand replicas for logtype index

MAINTAINERS.md
Spell the username as chosen by the person on GitHub. While GitHub is not case-sensitive, it does redirect to the correct spelling and we kept maintainer audit tools in https://github.com/opensearch-project/project-tools case-sensitive on those to avoid eLiTe type re-spelling and such.
=> Match maintainer account username.

.github/workflows/ci.yml, src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java, src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java, src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java, src/test/java/org/opensearch/securityanalytics/correlation/CorrelationEngineRestApiIT.java
=> fix flaky integration tests

src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
=> ignore tests that may be flaky

src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java, src/test/java/org/opensearch/securityanalytics/resthandler/RuleRestApiIT.java
If there are duplicate rules, the rules would overwrite each other when they are in different categories. This modifies the document id for the rule, so they dont overwrite each other.
#610 
=> Change ruleId if it exists

src/main/java/org/opensearch/securityanalytics/action/IndexCustomLogTypeRequest.java, src/main/java/org/opensearch/securityanalytics/model/CustomLogType.java, src/main/resources/OSMapping/logtypes.json, src/main/resources/mappings/log_type_config_mapping.json, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/resthandler/CustomLogTypeRestApiIT.java
add category to custom log types
=> add category to custom log types

src/main/java/org/opensearch/securityanalytics/findings/FindingsService.java, src/main/java/org/opensearch/securityanalytics/model/Rule.java, src/main/java/org/opensearch/securityanalytics/rules/aggregation/AggregationItem.java, src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java, src/main/java/org/opensearch/securityanalytics/rules/backend/QueryBackend.java, src/main/java/org/opensearch/securityanalytics/rules/objects/SigmaDetections.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/RuleRestApiIT.java, src/test/java/org/opensearch/securityanalytics/rules/aggregation/AggregationBackendTests.java, src/test/java/org/opensearch/securityanalytics/rules/condition/ConditionTests.java, src/test/java/org/opensearch/securityanalytics/rules/objects/SigmaDetectionsTests.java, src/test/java/org/opensearch/securityanalytics/rules/objects/SigmaRuleTests.java
Sigma Aggregation rule fixes
#458 
#558 
=> Sigma Aggregation rule fixes

src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java, src/main/java/org/opensearch/securityanalytics/correlation/VectorEmbeddingsEngine.java, src/main/java/org/opensearch/securityanalytics/logtype/LogTypeService.java, src/main/java/org/opensearch/securityanalytics/resthandler/RestSearchRuleAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteCorrelationRuleAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteCustomLogTypeAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteRuleAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexCustomLogTypeAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexRuleAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportListCorrelationAction.java, src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java
Change rest status on search request timeouts to be a transient error: `REQUEST_TIMEOUT`
[#502](https://github.com/opensearch-project/security-analytics/issues/502)
=> Address search request timeouts as transient error

src/main/resources/OSMapping/logtypes.json, src/main/resources/OSMapping/waf_logtype.json, src/main/resources/rules/waf/aws_waf/aws_waf_web_susp_useragents.yml, src/main/resources/rules/waf/aws_waf/aws_web_susp_useragents.yml, src/main/resources/rules/waf/web_cve_2023_25717_ruckus_wireless_admin_exploit_attempt.yml, src/main/resources/rules/waf/web_sql_injection_in_access_logs.yml, src/main/resources/rules/waf/web_susp_useragents.yml, src/main/resources/rules/waf/web_xss_in_access_logs.yml, src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/CustomLogTypeRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/RuleRestApiIT.java, src/test/resources/waf-sample.json
Adding WAF log type as a pre-packaged rule
Resolves https://github.com/opensearch-project/security-analytics/issues/573
=> Adding WAF Log type

src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/RuleRestApiIT.java
backports[Change ruleId if it exists](https://github.com/opensearch-project/security-analytics/pull/628)
backports[Fixes detectorType incompatibility with detector rules](https://github.com/opensearch-project/security-analytics/pull/524)
=> 2.9 backports

src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/resthandler/RuleRestApiIT.java
return rule fields which do not have aliases in the `get mappings view api`.
#620 
=> return rule fields which do not have aliases

src/main/java/org/opensearch/securityanalytics/model/Detector.java, src/test/java/org/opensearch/securityanalytics/model/WriteableTests.java
fix detector writeTo() method missing fields. 
Fixes flaky test `org.opensearch.securityanalytics.model.WriteableTests.testDetectorAsAStream()`
=> fix detector writeTo() method missing fields

src/main/java/org/opensearch/securityanalytics/threatIntel/DetectorThreatIntelService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/ThreatIntelFeedDataService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/action/ThreatIntelIndicesResponse.java, src/main/java/org/opensearch/securityanalytics/threatIntel/action/TransportPutTIFJobAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFJobParameterService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFJobRunner.java, src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFJobUpdateService.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/test/java/org/opensearch/securityanalytics/threatIntel/action/TransportPutTIFJobActionTests.java, src/test/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFJobParameterServiceTests.java, src/test/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFJobRunnerTests.java, src/test/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFJobUpdateServiceTests.java
this pr changes the logic of threat intel implementation to use listeners.
=> make threat intel async

src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java, src/main/resources/rules/test_windows/win_sample_rule.yml, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/rules/backend/QueryBackendTests.java
Changes the query construction of keywords in sigma rules from ```(_0:"value")``` to ```("value")``` to create a query string query without a designated field so that the keywords are instead matched against all the fields in a document.
#683 
=> #683 Sigma keywords field not handled correctly

src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java, src/test/java/org/opensearch/securityanalytics/DetectorThreatIntelIT.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/rules/backend/QueryBackendTests.java
Null filters in Sigma rules are not translated properly to queries leading to False Positives and broken detections.
They are being treated as term query to match field to value "null" instead of checking if value is nullable or field not exists.
This change fixes the query string query for the null filter conversion from sigma to backend search query
#683
=> fix null query filter conversion from sigma to query string query

src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/rules/backend/QueryBackendTests.java
=> [2.9] Backport [#722] fix null query filter conversion from sigma to query string query

src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java, src/main/java/org/opensearch/securityanalytics/mapper/MappingsTraverser.java, src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java, src/test/java/org/opensearch/securityanalytics/mapper/MappingsTraverserTests.java
Returns an empty response instead of exception in case of:
1. empty index mappings are present,
2. no applied aliases are present on the index
https://github.com/opensearch-project/security-analytics/issues/709
=> #709 Return empty response for empty mappings and no applied aliases

src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java, src/main/java/org/opensearch/securityanalytics/model/CorrelationQuery.java, src/main/java/org/opensearch/securityanalytics/model/CorrelationRule.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/correlation/CorrelationEngineRestApiIT.java
add field based rules support in correlation engine
2.9 manual backport of pr https://github.com/opensearch-project/security-analytics/pull/737
=> add field based rules support in correlation engine

src/test/java/org/opensearch/securityanalytics/threatIntel/integTests/TIFJobExtensionPluginIT.java
Fixes the threat intel plugin test when  security is enabled
=> Fix threat intel plugin integ test

build.gradle, src/main/java/org/opensearch/securityanalytics/logtype/LogTypeService.java, src/test/java/org/opensearch/securityanalytics/LogTypeServiceTests.java
Sets the ```log_type_mapping_version``` in ```LogTypeService.java``` to the same schema version values used in ```log_type_config_mapping.json```
#708 
=> Use a common constant to specify the version for log type mappings #708

src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteCustomLogTypeAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteRuleAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexCustomLogTypeAction.java, src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java, src/test/java/org/opensearch/securityanalytics/resthandler/CustomLogTypeRestApiIT.java
In the case when the detector index is present, but the custom rule index is missing, we want to allow the deletion of custom log types to be successful instead of throwing an error.
#700 
=> Allow deletion of custom log type if custom rule index is missing

src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteCustomLogTypeAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteRuleAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexCustomLogTypeAction.java, src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java, src/test/java/org/opensearch/securityanalytics/resthandler/CustomLogTypeRestApiIT.java
In the case when the custom rule index is missing, we want to allow the update/deletion of custom log types to be successful instead of throwing an error. The detector index may not be present, and the custom log types will still get updated/deleted respectively.
Backport #767 
#700 
=> Allow deletion of custom log type if custom rule index is missing (#767)

src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java, src/main/java/org/opensearch/securityanalytics/mapper/MappingsTraverser.java, src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java, src/test/java/org/opensearch/securityanalytics/mapper/MappingsTraverserTests.java
Returns an empty response instead of exception in case of:
1. empty index mappings are present,
2. no applied aliases are present on the index
#709 
=> * #709 Return empty response for empty mappings and no applied aliases

src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java, src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
When workflow usage is enabled, deleting a detector after the workflow has been deleted will fail with a "Workflow not found" exception. This PR adds logic to check for a 404 on workflow deletion and proceed with detector deletion if so.
Partially https://github.com/opensearch-project/security-analytics/issues/618
Related PR: https://github.com/opensearch-project/alerting/pull/1346
- [N/A] New functionality has javadoc added
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certific …
=> Delete detector successfully if workflow is missing

.github/CODEOWNERS
Fix codeowners to match maintainers as AWSHurneyt was put in and didn't match the entry in the Maintainers file. 
N/A
=> Fix codeowners to match maintainers

src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java, src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
* Delete detector successfully if workflow is missing
Signed-off-by: Chase Engelbrecht <engechas@amazon.com>
* Refactor to use existing NotFound exception checker
Signed-off-by: Chase Engelbrecht <engechas@amazon.com>
---------
Signed-off-by: Chase Engelbrecht <engechas@amazon.com>
(cherry picked from commit 0ad91ccecd846439bb3136390e2defbf59eb9e10)
Manual conflict resolution + backport
- [N/A] New functionality has javadoc added
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-cer …
=> Delete detector successfully if workflow is missing (#790)

src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java, src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java, src/main/java/org/opensearch/securityanalytics/model/CorrelationQuery.java, src/main/java/org/opensearch/securityanalytics/model/CorrelationRule.java, src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java, src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java, src/main/resources/mappings/finding_mapping.json, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/correlation/CorrelationEngineRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/rules/aggregation/AggregationBackendTests.java
=> [Backport 2.x] #737 add field based rules support in correlation engine

build.gradle
fix CVE-2023-2976 for google guava #511 
=> fix CVE-2023-2976

src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
Fixes the following issues:
1. In case the detector search request returns empty hits, the exception should be gracefully handled and checked before.
2. Case when multiple detectors are present and we are fetching only one detector.
#842  
=> [BUG] ArrayIndexOutOfBoundsException for inconsistent detector index behavior 

src/main/java/org/opensearch/securityanalytics/correlation/VectorEmbeddingsEngine.java
Checks if the detector type is missing in the log types index and handle the edge case gracefully.
#844 
=> Fail the flow the when detector type is missing in the log types index

src/main/java/org/opensearch/securityanalytics/correlation/VectorEmbeddingsEngine.java, src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
While dealing with correlations, we noticed unexpectedly high resource consumption in CPU and JVM, resulting in node drops. Upon closer examination, we found a subset of subscribe/findings tasks consistently in a hanging state throughout the data node's lifecycle until it either dropped or required manual restart. This information can be corroborated through the _cat/tasks API. 
The root cause of these hanging tasks was the way action listeners handle exceptions today, causing the parent listener to not close in some cases, if the exceptions are not caught correctly.
In this specific case, the exception causing the contention of resources was:
`
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
at org.opensearch.securityanalytics.correlation.VectorEmbeddingsEngin …
=> Fixing hanging tasks for correlations

src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java, src/main/java/org/opensearch/securityanalytics/correlation/VectorEmbeddingsEngine.java, src/main/java/org/opensearch/securityanalytics/logtype/LogTypeService.java, src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java, src/main/java/org/opensearch/securityanalytics/util/CorrelationIndices.java
This PR is intended to fix the hanging tasks observed in _cat/tasks by refactoring the correlation workflow to ensure timely closure of parent action listeners upon successful completion or encountering exceptions, and consolidating exception handling logic into a centralized function. The aim is to optimize task management efficiency and enhance the overall reliability of our system.
This logic has been tested against a high indexing workload ( approx. 1 M docs/ minute) where the issue was observed prominently in a cluster of 3 or more data nodes, and generating findings with the help of a Cloudtrail logs detector running all 32 pre-packaged rules at a frequency of 1 minute. Further, the correlations were generated with the help of a single rule on the same log type for testing, where …
=> Refactor invocation of Action listeners in correlations

src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java, src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/OCSFDetectorRestApiIT.java
An ecs field may have multiple raw fields associated with it. Currently, in the `getMappingsView` api, the ecs field will only map to one raw field. The new implementation will automatically map the ecs field to whatever field is present in the index. If multiple raw fields are present in an index, it will automatically map to one of the raw fields and add the other(s) into the `unmappedIndexFields` list.
This PR also removes duplicates from the `unmappedFieldAliases` list.
#786 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer …
=> Fix duplicate ecs mappings which returns incorrect log index field in mapping view API (#786)

src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java, src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/OCSFDetectorRestApiIT.java
Manual backport #788 to 2.x
---------
=> [Backport 2.x] Fix duplicate ecs mappings which returns incorrect log index field in mapping view API (#786) #889

src/main/java/org/opensearch/securityanalytics/rules/objects/SigmaDetectionItem.java, src/test/java/org/opensearch/securityanalytics/rules/backend/QueryBackendTests.java
Manual backport of #860 to 2.x
---------
=> [Backport 2.x] Add throw for empty strings in rules with modifier contains, startwith, and endswith (#860)

src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java, src/main/java/org/opensearch/securityanalytics/correlation/VectorEmbeddingsEngine.java, src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
Add search request timeouts to close hanging tasks for correlations waiting on searches.
#879
=> Add search request timeouts for correlations workflows

src/main/java/org/opensearch/securityanalytics/logtype/LogTypeService.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/resthandler/OCSFDetectorRestApiIT.java
Currently the get mappings view api incorrectly returns the ecs path for logs with ocsf or raw field types if a custom rule is created using a raw field. This is because whenever a new rule is created, the rule field(s) gets indexed into `.opensearch-sap-log-types-config` index along with the log_type (ex. below). However, because there are already preset mappings defined for certain log types like `cloudtrail`, the raw_field, ecs, and ocsf mappings are already defined in this index. Then when the get Mappings view API is called, the new document from the custom rule overwrites the existing predefined mapping which causes the ecs format to be incorrectly returned.
```
{
"_index": ".opensearch-sap-log-types-config",
"_id": "aws.cloudtrail.event_name|",
"_score": 1,
"_source": { …
```
=> Fix get mappings view API incorrectly returning ecs path

src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java, src/main/resources/rules/test_windows/win_sample_rule.yml, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/rules/backend/QueryBackendTests.java
Backports https://github.com/opensearch-project/security-analytics/pull/725 to 2.7
=> [Backport 2.7] #725 Sigma keywords field not handled correctly

src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java, src/main/resources/rules/test_windows/win_sample_rule.yml, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/rules/backend/QueryBackendTests.java
Backport https://github.com/opensearch-project/security-analytics/pull/725 to 2.8
=> [Backport 2.8] #725 Sigma keywords field not handled correctly

src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java, src/main/resources/rules/test_windows/win_sample_rule.yml, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/rules/backend/QueryBackendTests.java
Backport https://github.com/opensearch-project/security-analytics/pull/725 to 2.6
=> [Backport 2.6] #725 Sigma keywords field not handled correctly

src/test/java/org/opensearch/securityanalytics/resthandler/OCSFDetectorRestApiIT.java
Fixes the broken integration test raised in this PR #867 
=> Fixes OCSF integ test

src/main/java/org/opensearch/securityanalytics/action/GetFindingsRequest.java, src/main/java/org/opensearch/securityanalytics/findings/FindingsService.java, src/main/java/org/opensearch/securityanalytics/resthandler/RestGetFindingsAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportGetFindingsAction.java, src/main/java/org/opensearch/securityanalytics/util/DetectorUtils.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/findings/FindingIT.java, src/test/java/org/opensearch/securityanalytics/findings/FindingServiceTests.java, src/test/java/org/opensearch/securityanalytics/findings/SecureFindingRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/OCSFDetectorRestApiIT.java
Manual backport to 2.x 
- #803 
- #918 
- #914 
=> [Backport to 2.x] Backport to 2.x #803, #918, and #914

build.gradle, src/main/java/org/opensearch/securityanalytics/indexmanagment/DetectorIndexManagementService.java, src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java, src/main/java/org/opensearch/securityanalytics/model/Detector.java, src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java, src/main/java/org/opensearch/securityanalytics/rules/backend/QueryBackend.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java, src/main/resources/mappings/rules.json, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java, src/test/java/org/opensearch/securityanalytics/model/WriteableTests.java, src/test/java/org/opensearch/securityanalytics/rules/backend/QueryBackendTests.java
* Backports #335 #203 #695 #722 #873 
* Bump build version to 2.5.1
* Fix build
=> Backports for 2.5

src/main/java/org/opensearch/securityanalytics/logtype/LogTypeService.java, src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java, src/main/java/org/opensearch/securityanalytics/model/Detector.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/findings/FindingIT.java, src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java, src/test/java/org/opensearch/securityanalytics/model/WriteableTests.java, src/test/java/org/opensearch/securityanalytics/resthandler/OCSFDetectorRestApiIT.java
Backport PRs:
* https://github.com/opensearch-project/security-analytics/pull/918
* https://github.com/opensearch-project/security-analytics/pull/867
* https://github.com/opensearch-project/security-analytics/pull/788
* https://github.com/opensearch-project/security-analytics/pull/695
=> Backport 2.9 fix

build.gradle, src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java, src/main/java/org/opensearch/securityanalytics/mapper/MapperUtils.java, src/main/java/org/opensearch/securityanalytics/model/Detector.java, src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/mapper/MappingsTraverserTests.java, src/test/java/org/opensearch/securityanalytics/model/WriteableTests.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/rules/backend/QueryBackendTests.java
Backports https://github.com/opensearch-project/security-analytics/pull/695 https://github.com/opensearch-project/security-analytics/pull/722 https://github.com/opensearch-project/security-analytics/pull/724 https://github.com/opensearch-project/security-analytics/pull/873
- Bump build version to 2.7.1
- Fix build
=> Security Analytics 2.7 Backports

src/main/java/org/opensearch/securityanalytics/model/Detector.java, src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/main/java/org/opensearch/securityanalytics/util/ExceptionChecker.java, src/main/java/org/opensearch/securityanalytics/util/ThrowableCheckingPredicates.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/util/ExceptionCheckerTests.java, src/test/java/org/opensearch/securityanalytics/util/ThrowableCheckingPredicatesTests.java
Related to #790. Adds logic to allow a user to stop a detector when the underlying workflow is deleted. Also adds an actionable exception when trying to edit or start a detector after the underlying workflow has been deleted.
#618  
- [N/A] New functionality has javadoc added
=> Allow detectors to be stopped if underlying workflow is deleted. Don't allow them to then be started/editted

src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java
When a sigma rule has a keywords structure (example below), we do not want to include a field value in the `ruleQueryFields` because there is no field associated with a keyword.
```
Ex:
condition: selection_1
selection1:
- keyword1
```
PR also adds comments to clarify methods meaning.
=> Fix keywords bug incorrectly adding field value

src/main/java/org/opensearch/securityanalytics/model/Detector.java, src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/main/java/org/opensearch/securityanalytics/util/ExceptionChecker.java, src/main/java/org/opensearch/securityanalytics/util/ThrowableCheckingPredicates.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/util/ExceptionCheckerTests.java, src/test/java/org/opensearch/securityanalytics/util/ThrowableCheckingPredicatesTests.java
Manual backport of #810 to 2.10
=> Allow detectors to be stopped if underlying workflow is deleted. Don't allow them to then be started/edited (#810)

src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java
Manual backport of https://github.com/opensearch-project/security-analytics/pull/964
=> [Backport 2.7] Fix keywords bug incorrectly adding field value (#964)

src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java
Manual backport of https://github.com/opensearch-project/security-analytics/pull/964
=> [Backport 2.9] Fix keywords bug incorrectly adding field value (#964)

MAINTAINERS.md
=> Fix: typo.

src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/main/java/org/opensearch/securityanalytics/util/DetectorUtils.java, src/main/java/org/opensearch/securityanalytics/util/WorkflowService.java, src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java
remove check for agg rules in detector trigger condition to create chained findings monitor.
Currently, chained findings monitor is not created unless ids of aggregation Sigma rules are not mentioned in the detector trigger condition
Right behaviour is to create chained findings monitor irrespective of trigger condition.
Add agg rule tags to chained findings monitor
=> [BUG_FIX] fix check for agg rules in detector trigger condition to create chained findings monitor

src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/main/java/org/opensearch/securityanalytics/util/DetectorUtils.java, src/main/java/org/opensearch/securityanalytics/util/WorkflowService.java, src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java
Backports #992 to 2.x
* remove chekc for agg rules in detector trigger condition to create bucket level monitor
* add agg rules tags in chained monitor query to match trigger condition of detector
* fix check to evaluate agg rules present when creating chained findings monitor
* fix tests where check on group by trigger existed earlier
* fix race condition while creating first monitor
* add test to verify detector trigger function for aggregation rules
* revert step listener change
---------
For more information on following Developer Certificate of Origin and signing off your commits, please check …
=> Backports #992 to 2.x

src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/main/java/org/opensearch/securityanalytics/util/DetectorUtils.java, src/main/java/org/opensearch/securityanalytics/util/WorkflowService.java, src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java
fix check for agg rules in detector trigger condition to create chained findings monitor (#992)
* remove chekc for agg rules in detector trigger condition to create bucket level monitor
* add agg rules tags in chained monitor query to match trigger condition of detector
* fix check to evaluate agg rules present when creating chained findings monitor
* fix tests where check on group by trigger existed earlier
* fix race condition while creating first monitor
* add test to verify detector trigger function for aggregation rules
* revert step listener change
---------
For more information on following …
=> [Backport #992 to 2.11] 

release-notes/opensearch-security-analytics.release-notes-2.14.0.0.md
Added 2.14.0 release notes.
https://github.com/opensearch-project/security-analytics/issues/951
=> Added 2.14.0 release notes.

src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java, src/test/java/org/opensearch/securityanalytics/correlation/CorrelationEngineRestApiIT.java, src/test/java/org/opensearch/securityanalytics/findings/FindingIT.java, src/test/java/org/opensearch/securityanalytics/findings/SecureFindingRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/threatIntel/integTests/ThreatIntelJobRunnerIT.java
this pr identifies flaky integ tests & make security-analytics integTest CI stable
https://github.com/opensearch-project/security-analytics/issues/985
https://github.com/opensearch-project/security-analytics/issues/965
https://github.com/opensearch-project/security-analytics/issues/939
=> make security-analytics integTest stable

src/main/java/org/opensearch/securityanalytics/findings/FindingsService.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
Currently when updating a detector with aggegation rules, the chained finding doc levelmonitor is getting deleted
This PR fixes the logic to update/retain the chained  finding doc level monitor
Added to integ test to verify detector behaviour after updating detector.
=> fix chained findings monitor logic in update detector flow

src/main/java/org/opensearch/securityanalytics/model/IoCMatch.java, src/main/resources/mappings/ioc_match_mapping.json, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/model/IoCMatchTests.java
An Ioc Match is an entity that is created as part of malicious Ioc Scanning
Ioc match maps an IoC to a list of documents that contain the ioc
Ioc match primarily contains the following information:
- ioc value
- ioc type
- ioc scan job id
- list of doc ids that are found to contain the ioc in the format doc_id:index_name
- the feeds that had marked the IoC as malicious at that point in time
- timestamp 
- the execution id of the job (just a unique string to mark the execution)
It's in essence the reverse mapping of a finding that maps a document to a list of malicious IoCs found
For more information on following Developer Certificate of …
=> Ioc match model

src/main/java/org/opensearch/securityanalytics/action/GetAlertsRequest.java, src/main/java/org/opensearch/securityanalytics/alerts/AlertsService.java, src/main/java/org/opensearch/securityanalytics/resthandler/RestGetAlertsAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportAcknowledgeAlertsAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportGetAlertsAction.java, src/test/java/org/opensearch/securityanalytics/alerts/AlertingServiceTests.java, src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
changes to add start_time and end_time filters to GetAlertsRequest
=> changes to add start_time and end_time filters to GetAlertsRequest

src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java, src/main/java/org/opensearch/securityanalytics/model/IocDao.java, src/main/java/org/opensearch/securityanalytics/model/IocDto.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/model/IocDaoTests.java, src/test/java/org/opensearch/securityanalytics/model/IocDtoTests.java
These are the references I'm using.
**Domain documentation**
Section "6.4 Domain Name Object" of https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_k017w16zutw
**Hash documentation**
https://stix2.readthedocs.io/en/latest/guide/serializing.html
**IP documentation**
"6.8 IPv4 Address Object" section of https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_wh296fiwpklp
=> Rough draft of IOC data model.

src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFeedStore.java, src/main/java/org/opensearch/securityanalytics/threatIntel/model/DefaultIocStoreConfig.java, src/test/java/org/opensearch/securityanalytics/resthandler/SATIFSourceConfigRestApiIT.java
=> Fix ioc store config mappings

src/main/java/org/opensearch/securityanalytics/threatIntel/action/SASearchTIFSourceConfigsRequest.java, src/main/java/org/opensearch/securityanalytics/threatIntel/resthandler/RestSearchTIFSourceConfigsAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportSearchTIFSourceConfigsAction.java
Changes the search source config request type to take in a searchSourceBuilder so that the search request can be built in the service layer
=> Change search source config request

src/main/java/org/opensearch/securityanalytics/model/STIX2IOC.java, src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java, src/main/java/org/opensearch/securityanalytics/services/STIX2IOCConsumer.java, src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFeedStore.java, src/test/java/org/opensearch/securityanalytics/util/STIX2IOCGenerator.java
1. Moved "feed" variables from generic STIX2 model in SA-commons to STIX2IOC model as those variables are specific to security analytics functionality. 
2. Added feedName variables to STIX2IOC.
This PR is dependent on PR https://github.com/opensearch-project/security-analytics-commons/pull/10
=> Added "feedName" to IOC model.

src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java, src/main/java/org/opensearch/securityanalytics/action/ListIOCsActionRequest.java, src/main/java/org/opensearch/securityanalytics/action/ListIOCsActionResponse.java, src/main/java/org/opensearch/securityanalytics/model/DetailedSTIX2IOCDto.java, src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java, src/main/java/org/opensearch/securityanalytics/resthandler/RestListIOCsAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java, src/test/java/org/opensearch/securityanalytics/model/DetailedSTIX2IOCDtoTests.java, src/test/java/org/opensearch/securityanalytics/resthandler/ListIOCsRestApiIT.java, src/test/java/org/opensearch/securityanalytics/util/STIX2IOCGenerator.java
Made feedId, and type params of ListIOCsActionRequest support lists of strings.
=> ListIOCs API support lists of feedIds, and types.

src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java, src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFeedStore.java, src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java, src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigService.java, src/test/java/org/opensearch/securityanalytics/resthandler/ListIOCsRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/SATIFSourceConfigRestApiIT.java
Rollsover ioc indices based on age of index and number of indices associated with an alias. Deletes the old ioc indices
=> Logic to delete old iocs and add ioc index rollover

src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java, src/main/java/org/opensearch/securityanalytics/model/threatintel/ThreatIntelAlert.java, src/main/java/org/opensearch/securityanalytics/resthandler/RestGetThreatIntelAlertsAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/action/monitor/UpdateThreatIntelAlertStatusAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/action/monitor/request/GetThreatIntelAlertsRequest.java, src/main/java/org/opensearch/securityanalytics/threatIntel/action/monitor/request/UpdateThreatIntelAlertStatusRequest.java, src/main/java/org/opensearch/securityanalytics/threatIntel/action/monitor/response/GetThreatIntelAlertsResponse.java, src/main/java/org/opensearch/securityanalytics/threatIntel/action/monitor/response/UpdateThreatIntelAlertsStatusResponse.java, src/main/java/org/opensearch/securityanalytics/threatIntel/resthandler/monitor/RestUpdateThreatIntelAlertsStatusAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/sacommons/monitor/ThreatIntelMonitorActions.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportIndexThreatIntelMonitorAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportUpdateThreatIntelAlertStatusAction.java, src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java, src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelAlertIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java
=> adds threat intel alert status update API 

build.gradle, src/main/java/org/opensearch/securityanalytics/model/DetailedSTIX2IOCDto.java, src/main/java/org/opensearch/securityanalytics/model/STIX2IOC.java, src/main/java/org/opensearch/securityanalytics/services/STIX2IOCConnectorFactory.java, src/main/java/org/opensearch/securityanalytics/services/STIX2IOCConsumer.java, src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java, src/main/java/org/opensearch/securityanalytics/transport/TransportTestS3ConnectionAction.java
1. Implemented support for making calls to S3 using either S3Client, or AmazonS3. Dependency on S3Client will eventually be removed.
2. Added support for consuming security analytics commons directly from project rootDir.
=> Refactored calls to S3. Added support for consuming security analytics commons directly from project rootDir.

src/main/java/org/opensearch/securityanalytics/model/STIX2IOC.java, src/main/plugin-metadata/plugin-security.policy, src/main/resources/mappings/threat_intel_job_mapping.json, src/test/java/org/opensearch/securityanalytics/resthandler/SATIFSourceConfigRestApiIT.java
1. Adjusted IOC type enums.
2. Fixed security policy for deserialization.
`SATIFSourceConfigRestApiIT` tests pass locally.
=> Adjusted IOC type enums.

src/test/java/org/opensearch/securityanalytics/resthandler/SATIFSourceConfigRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/TestS3ConnectionRestIT.java
As mentioned in https://github.com/opensearch-project/security-analytics/pull/1098#issuecomment-2200635491, the `TestS3ConnectionRestIT`, and `SATIFSourceConfigRestApiIT` tests cannot currently be executed via github CI as they require additional input params. 
Will discuss onboarding to github secrets with the build team to securely provide those params, and will raise a separate PR to remove the `@Ignore` annotations.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin …
=> Ignore feature tests that cannot execute in gjthub CI.

src/main/java/org/opensearch/securityanalytics/correlation/alert/CorrelationAlertService.java
* Send empty array during indexNotFound exception
=> set blank response when indexNotFound exception

src/main/java/org/opensearch/securityanalytics/services/STIX2IOCConsumer.java, src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportGetIocFindingsAction.java
=> throw error when no iocs are stored due to incompatible ioc types from S3 downloaded iocs file

.github/workflows/ci.yml, .github/workflows/multi-node-test-workflow.yml, .github/workflows/security-test-workflow.yml
The gradle check on ubuntu and multi node is failing with below error.
```
/__e/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib6[4](https://github.com/opensearch-project/security-analytics/actions/runs/9784315745/job/27097381544?pr=1136#step:17:4)/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```
Created a similar PR like KNN https://github.com/opensearch-project/k-NN/pull/1795 to fix it. 
For more information on following Developer Certificate of Origin and signing off your commits, please check …
=> Fix build CI error due to action runner env upgrade node 20

src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java, src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/common/SourceConfigDtoValidator.java, src/main/java/org/opensearch/securityanalytics/threatIntel/common/SourceConfigType.java, src/main/java/org/opensearch/securityanalytics/threatIntel/model/IocUploadSource.java, src/main/java/org/opensearch/securityanalytics/threatIntel/model/Source.java, src/main/java/org/opensearch/securityanalytics/threatIntel/model/UrlDownloadSource.java, src/main/java/org/opensearch/securityanalytics/threatIntel/service/DefaultTifSourceConfigLoaderService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/service/TIFJobUpdateService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/service/ThreatIntelFeedDataService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportIndexTIFSourceConfigAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportSearchTIFSourceConfigsAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/util/ThreatIntelFeedParser.java, src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java, src/test/java/org/opensearch/securityanalytics/resthandler/SourceConfigWithoutS3RestApiIT.java
adds new tif source config type - url download
Downloads Iocs from a url of a given format and makes it available for scans and viewing Iocs
=> adds new tif source config type - url download

src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java, src/main/java/org/opensearch/securityanalytics/jobscheduler/SecurityAnalyticsRunner.java, src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/dao/BaseEntityCrudService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/model/TIFJobParameter.java, src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
Fixes the the job scheduler parser to be compatible with detector configured with threat intel, clean up the action listeners, and fixes multi-node test
=> Fix the job scheduler parser, action listeners, and multi-node test

src/main/java/org/opensearch/securityanalytics/model/DetailedSTIX2IOCDto.java, src/main/java/org/opensearch/securityanalytics/model/STIX2IOC.java, src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java, src/main/java/org/opensearch/securityanalytics/services/STIX2IOCConnectorFactory.java, src/main/java/org/opensearch/securityanalytics/services/STIX2IOCConsumer.java, src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFeedStore.java, src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/common/SourceConfigDtoValidator.java, src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/service/SaIoCScanService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/model/DefaultIocStoreConfig.java, src/main/java/org/opensearch/securityanalytics/threatIntel/service/DefaultTifSourceConfigLoaderService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/model/SATIFSourceConfigTests.java, src/test/java/org/opensearch/securityanalytics/resthandler/SATIFSourceConfigRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/SourceConfigWithoutS3RestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/util/STIX2IOCGenerator.java
=> [Backport 2.15] Adjusted IOCTypes usage. (#1156)

src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/dto/IocScanContext.java, src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/service/IoCScanService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/model/monitor/TransportThreatIntelMonitorFanOutAction.java, src/main/java/org/opensearch/securityanalytics/util/IndexUtils.java, src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java, src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java
BUG: threat intel monitor not working on aliases in input
FIX: Currently `per_ioc_type_scan_input_list` field in monitor contains a map of index to the fields. This index input could be an alias. while executing monitor and dealing with concrete indices we would have to re-resolve the indices to create mapping of conrete index to the monitor input indices
=> [BUG] Resolve aliases in monitor input to concrete indices before computing ioc-containing fields from concrete index docs

src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigService.java, src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java, src/test/java/org/opensearch/securityanalytics/resthandler/SourceConfigWithoutS3RestApiIT.java
Fixes the ioc upload behavior when retaining old ioc indices. Previously used to delete ioc indices when source config gets indexed but now has the same behavior as s3 download where the background delete job will delete old ioc indices.
Also changes internal server errors to bad requests.
=> Fix ioc upload update behavior and change error response

src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportDeleteTIFSourceConfigAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportGetIocFindingsAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportGetTIFSourceConfigAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportIndexTIFSourceConfigAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportPutTIFJobAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportRefreshTIFSourceConfigAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportSearchTIFSourceConfigsAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportDeleteThreatIntelMonitorAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportGetThreatIntelAlertsAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportIndexThreatIntelMonitorAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportSearchThreatIntelMonitorAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportUpdateThreatIntelAlertStatusAction.java
Adds user validation for threat intel transport layer classes and stashes the thread context for all system index interactions
=> Adds user validation for threat intel transport layer classes and stashes the thread context for all system index interactions

build.gradle
update build.gradle to use alerting-spi snapshot version
#1193 
=> update build.gradle to use alerting-spi snapshot version

src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportGetThreatIntelAlertsAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportIndexThreatIntelMonitorAction.java, src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java
make threat intel run with standard detectors
=> make threat intel run with standard detectors

src/main/java/org/opensearch/securityanalytics/threatIntel/action/SAGetTIFSourceConfigResponse.java, src/main/java/org/opensearch/securityanalytics/threatIntel/action/SAIndexTIFSourceConfigResponse.java, src/main/java/org/opensearch/securityanalytics/threatIntel/common/TIFLockService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFSourceConfigDto.java, src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportIndexTIFSourceConfigAction.java, src/test/java/org/opensearch/securityanalytics/resthandler/SourceConfigWithoutS3RestApiIT.java
adds toggling refresh disable/enable for deactivate/activate operation while updating URL_DOWNLOAD type configs
=> adds toggling refresh disable/enable for deactivate/activate operation while updating URL_DOWNLOAD type configs

src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFJobRunner.java, src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java, src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportIndexTIFSourceConfigAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportPutTIFJobAction.java, src/test/java/org/opensearch/securityanalytics/threatIntel/common/ThreatIntelLockServiceTests.java
Refactors action listeners so that when releasing the lock for creating/updating/refreshing threat intel source config it's event driven.
Resolves #1224 
=> Make threat intel source config release lock event driven

src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java, src/test/java/org/opensearch/securityanalytics/resthandler/SATIFSourceConfigRestApiIT.java
When constructing and validating the S3 connector config, the errors thrown during validation are not caught by the action listener so subsequent actions to delete the created source config are not happening. This PR adds a try catch to catch these errors and fails the action listener.
=> Fix S3 validation errors not caught by action listener

src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigService.java, src/test/java/org/opensearch/securityanalytics/resthandler/SATIFSourceConfigRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/SourceConfigWithoutS3RestApiIT.java
Deletes and cleans up any ioc indices that were created by failed source configs. Also manually deletes the job scheduler lock for source configs that have the job disabled. When a source config job is enabled and then the source config is deleted, the lock is automatically deleted. However, the lock is not cleaned up if the job is disabled. This PR adds a change to check whether or not the job is enabled, if not then it will manually delete the associated lock when source config is deleted.
Resolves https://github.com/opensearch-project/security-analytics/issues/1255
For more information on following Developer Certificate of Origin and signing off your commits, please check …
=> Clean up empty IOC indices created by failed source configs

src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java, src/test/java/org/opensearch/securityanalytics/resthandler/SecureThreatIntelMonitorRestApiIT.java
Adds secure rest tests for threat intel monitor APIs
=> secure rest tests for threat intel monitor apis

src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFeedStore.java
Makes creating ioc indices async which fixes multi node tests failing with this error
```
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [.opensearch-sap-iocs-slcqo5eb8aruhdvnjh_--1723282892147/EJPu2uCgTVGmKFLsPdLUMA] already exists","index":".opensearch-sap-iocs-slcqo5eb8aruhdvnjh_--1723282892147","index_uuid":"EJPu2uCgTVGmKFLsPdLUMA"}],"type":"resource_already_exists_exception","reason":"index [.opensearch-sap-iocs-slcqo5eb8aruhdvnjh_--1723282892147/EJPu2uCgTVGmKFLsPdLUMA] already exists","index":".opensearch-sap-iocs-slcqo5eb8aruhdvnjh_--1723282892147","index_uuid":"EJPu2uCgTVGmKFLsPdLUMA"},"status":400}
at __randomizedtesting.SeedInfo.seed([F7F112DCB87B4FEA:BBA7EAA52758C64E]:0)
```
By …
=> Fix threat intel multinode tests

src/main/java/org/opensearch/securityanalytics/threatIntel/common/TIFLockService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFJobRunner.java, src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java, src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportIndexTIFSourceConfigAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportPutTIFJobAction.java, src/main/java/org/opensearch/securityanalytics/util/IndexUtils.java, src/main/resources/mappings/threat_intel_job_mapping.json, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/resthandler/SourceConfigWithoutS3RestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/threatIntel/common/ThreatIntelLockServiceTests.java
When upgrading cluster from older version (2.12 - 2.15) that has threat intel enabled to a newer version (2.16 >=) there's an discrepancy with the mapping in the job index (`.opensearch-sap--job`). This PR checks and updates the mapping for the job index if needed whenever a new source config is created.
Also returns listener on failure when releasing the threat intel lock
Resolves https://github.com/opensearch-project/security-analytics/issues/1247
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/security-analytics/blob/main/CONTRIBUTING.md#developer-certificate-of-origin) …
=> Update threat intel job mapping to new version

src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java, src/main/java/org/opensearch/securityanalytics/threatIntel/action/ListIOCsAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/action/ListIOCsActionRequest.java, src/main/java/org/opensearch/securityanalytics/threatIntel/action/ListIOCsActionResponse.java, src/main/java/org/opensearch/securityanalytics/threatIntel/resthandler/RestListIOCsAction.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportListIOCsAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java, src/test/java/org/opensearch/securityanalytics/resthandler/ListIOCsRestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/SourceConfigWithoutS3RestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java
Checks user permissions and stashes the context for the List IOCs api.
Also refactors the List IOCs API classes into the threat intel folder
=> Stash context for List IOCs Api

.github/workflows/ci.yml, .github/workflows/multi-node-test-workflow.yml, .github/workflows/security-test-workflow.yml, build.gradle
Manually incrementing the version to 2.13.1 to match other repos like common utils and alerting
Also cherry-picked these PRs to help CIs pass:
https://github.com/opensearch-project/security-analytics/pull/1143: node 20 upgrade
https://github.com/opensearch-project/security-analytics/pull/1305: upgrade upload artifacts
Issue for failing ITs: https://github.com/opensearch-project/security-analytics/issues/1313
=> version bump to 2.13.1

src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java, src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java, src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/service/IoCScanService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/service/SaIoCScanService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/model/monitor/TransportThreatIntelMonitorFanOutAction.java, src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java
[**handle exception arising from trying to search with sort on empty index**](https://github.com/opensearch-project/security-analytics/commit/9fd72e89e9ad6793a956b3d05870b04c70124eeb): Sorting by `_seq_no` field fails on empty index as mapping isn't created yet. This failure is expected and needs to be handled to return empty list instead of throwing exception and calling it a monitor failure
```
Caused by: org.opensearch.index.query.QueryShardException: No mapping found for [_seq_no] in order to sort on
at org.opensearch.search.sort.FieldSortBuilder.resolveUnmappedType(FieldSortBuilder.java:564) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
at org.opensearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:411) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
at …
```
=> threat intel monitor bug fixes

src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/service/IoCScanService.java, src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java
**This change adds null check while adding fetched iocs into per-indicator-type map to fix below issue**
Currently we are seeing a NullPointerException when there are multiple types of indicators configured in threat intel monitor.
```
[2024-10-02T13:58:22,195][ERROR][o.o.s.t.i.s.IoCScanService] [integTest-0] Threat intel monitor HOYGT5IBl5xy9GfJFbXV: Unexpected failure in running scan for 2 docs
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "fields" is null
at org.opensearch.securityanalytics.threatIntel.iocscan.service.IoCScanService.extractIocsPerType(IoCScanService.java:137) ~[opensearch-security-analytics-3.0.0.0-SNAPSHOT.jar:3.0.0.0-SNAPSHOT]
at org.opensearch.securityanalytics.threatIntel.iocscan.service.IoCScanService.scanIoCs(IoCScanService.java …
```
=> Add null check while adding fetched iocs into per-indicator-type map

src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/service/IoCScanService.java, src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java
Backport #1335 to 2.x
Autocut backport via CI failed due to constrcutor difference between 2.x and 3.x
=> Backport #1335 to 2.x

src/main/java/org/opensearch/securityanalytics/transport/TransportIndexRuleAction.java, src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/resthandler/RuleRestApiIT.java
**Description**
when custom rule is created we are not setting rule document id to the string passed in rule yaml in id field. we autogenerate the id
this change sets custom rule doc id to the id passed in rule yaml instead of autogenerated id
**Related Issues**
Resolves https://github.com/opensearch-project/security-analytics/issues/1301
=> set custom rule doc id to the id passed in rule yaml instead of autogenerated name

src/main/java/org/opensearch/securityanalytics/transport/TransportIndexRuleAction.java, src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/resthandler/RuleRestApiIT.java
Description
when custom rule is created we are not setting rule document id to the string passed in rule yaml in id field. we autogenerate the id
this change sets custom rule doc id to the id passed in rule yaml instead of autogenerated id
Related Issues
Resolves https://github.com/opensearch-project/security-analytics/issues/1301
=> [2.17] set custom rule doc id to the id passed in rule yaml instead of autogenerated name 

src/main/java/org/opensearch/securityanalytics/indexmanagment/DetectorIndexManagementService.java, src/main/java/org/opensearch/securityanalytics/logtype/LogTypeService.java, src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFeedStore.java, src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java, src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/dao/BaseEntityCrudService.java, src/main/java/org/opensearch/securityanalytics/util/CorrelationIndices.java, src/main/java/org/opensearch/securityanalytics/util/CorrelationRuleIndices.java, src/main/java/org/opensearch/securityanalytics/util/CustomLogTypeIndices.java, src/main/java/org/opensearch/securityanalytics/util/DetectorIndices.java, src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java
update number of replicas of system indices to 0-20 and number of primary shards for system indices to 1
=> update number of replicas of system indices to 1-20 and number of primary shards for system indices to 1

src/main/java/org/opensearch/securityanalytics/correlation/alert/notifications/NotificationService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/dao/BaseEntityCrudService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/service/IoCScanService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/service/SaIoCScanService.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java
1. Fixes listener leak in notification success
2. marks execution succeeded if findings generated and alerts creation fails.
3. marks execution succeeded if findings and alerts are generated but send notfication  fails.
we are doing 2. and 3. to avoid findings from being generated repeatedly and moving the marker forward for last seen docs in monitor metadata.
\
=> Fix notifications listener leak in threat intel monitor

src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
update min number of replicas to 0.
=> update min number of replicas to 0

src/main/java/org/opensearch/securityanalytics/mapper/IndexTemplateManager.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java, src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java
fix for detectors with sigma aggregation rules
=> fix for detectors with sigma aggregation rules

src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportListIOCsAction.java, src/test/java/org/opensearch/securityanalytics/resthandler/ListIOCsRestApiIT.java
1. Fixed total IOCs count capping at 10,000.
2. Fixed number of findings per IOC capping at 10,000.
Resolves #1191 
=> [Bug] Fixed ListIOCs number of findings cap.

src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportUpdateThreatIntelAlertStatusAction.java
Fixes search threat monitor query that fails when detectors are present. This fix was missed in update threat intel alert API
Similar to fix: [make threat intel run with standard detectors](https://github.com/opensearch-project/security-analytics/pull/1234 )
=> fix search monitor query in update threat intel alert status API

src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportUpdateThreatIntelAlertStatusAction.java
Backport https://github.com/opensearch-project/security-analytics/commit/3d1fcd5be64a5d656693392a5b55f1e005be38e4 from https://github.com/opensearch-project/security-analytics/pull/1383.
=> [Backport 2.15] fix search monitor query in update threat intel alert status API

src/main/java/org/opensearch/securityanalytics/correlation/alert/CorrelationAlertService.java
* set the refresh policy to IMMEDIATE when acknowledging correlation alerts
=> set the refresh policy to IMMEDIATE when updating correlation alerts

src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFeedStore.java
Added check to prevent resource_already_exists_exception when indexing more than 10k iocs.
=> [Bug] Add exists check for IOCs index.

src/main/java/org/opensearch/securityanalytics/threatIntel/common/SourceConfigDtoValidator.java, src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFSourceConfig.java, src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFSourceConfigDto.java, src/test/java/org/opensearch/securityanalytics/action/IndexTIFSourceConfigRequestTests.java, src/test/java/org/opensearch/securityanalytics/model/SATIFSourceConfigDtoTests.java, src/test/java/org/opensearch/securityanalytics/model/SATIFSourceConfigTests.java
Add source config validation so source config cannot be created without valid `name`, `type`, `format`, `source`, and `ioc type`. Additionally allows source configs with null values to still be read and deleted.
Resolves #1366
=> Add validation for threat intel source config

src/main/java/org/opensearch/securityanalytics/logtype/LogTypeService.java, src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java, src/main/java/org/opensearch/securityanalytics/model/LogType.java, src/main/resources/OSMapping/cloudtrail_logtype.json, src/main/resources/OSMapping/dns_logtype.json, src/main/resources/OSMapping/network_logtype.json, src/main/resources/OSMapping/vpcflow_logtype.json, src/main/resources/OSMapping/waf_logtype.json, src/main/resources/OSMapping/windows_logtype.json, src/test/java/org/opensearch/securityanalytics/LogTypeServiceTests.java, src/test/java/org/opensearch/securityanalytics/model/WriteableTests.java, src/test/java/org/opensearch/securityanalytics/resthandler/OCSFDetectorRestApiIT.java, src/test/java/org/opensearch/securityanalytics/writable/LogTypeTests.java
Adds various OCSF 1.1 field mappings to the static mappings repository in Security Analytics, allowing for more automatic field mappings during detector creation on indices ingesting OCSF 1.1 logs from Security Lake.
=> Adding various OCSF 1.1 fields to log type static mappings

.github/workflows/ci.yml, .github/workflows/maven-publish.yml, .github/workflows/multi-node-test-workflow.yml, .github/workflows/security-test-workflow.yml, src/main/java/org/opensearch/securityanalytics/alerts/AlertsService.java, src/main/java/org/opensearch/securityanalytics/threatIntel/transport/monitor/TransportIndexThreatIntelMonitorAction.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/main/java/org/opensearch/securityanalytics/util/WorkflowService.java, src/test/java/org/opensearch/securityanalytics/alerts/AlertingServiceTests.java, src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java, src/test/java/org/opensearch/securityanalytics/threatIntel/model/monitor/ThreatIntelInputTests.java
This pr proposes optimizations for sigma aggregation rule based detectors execution workflow.
- Filters out only alerts generated from match all doc-level monitors. https://github.com/opensearch-project/security-analytics/pull/1418/files#diff-dd990d08c350d0f4c1c87148dffbdd5bdaf50dcfd9b22c9bba0fe10bb1930ce7R89
- pass an additional flag to ignore findings and alerts generated from chained doc-level monitors. https://github.com/opensearch-project/security-analytics/pull/1418/files#diff-8fa8978eef6244554fff1512eb4ed63755d995cf3e8aa295522657a4eecb6166R905
- fixes a bug in update scenario of chained bucket-level doc-level monitors. https://github.com/opensearch-project/security-analytics/pull/1418/files#diff-ac84d76e5ec563a48e1e18eeedca280d589c79bcb29cbc2fce8d8bf6d3097928R103
- upgrade artifact …
=> optimize sigma aggregation rule based detectors execution workflow

src/main/java/org/opensearch/securityanalytics/model/DetectorTrigger.java, src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java, src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
Since detectors with sigme aggregation rules create a single match_all doc level monitor to perform chained findings, we cannot use query_id of the doc level monitor to perform trigger condition where alerts are created on rule matches.
We add the rule id to tag so that we can create doc level trigger condition to match something like `
**_(query[tag=cloudtrail]) && (query[tag=agg_rule_id1] || query [tag=agg_rule_id2])**
instead of doing (query[tag=cloudtrail]) && (query[id=agg_rule_id1] || query [id=agg_rule_id2])
since query id of chained findings doc level monitor cannot associate to multiple agg rules that it will alert for.
=> test update detector with aggregation rules

src/main/java/org/opensearch/securityanalytics/mapper/MapperService.java, src/main/resources/OSMapping/waf_logtype.json, src/test/java/org/opensearch/securityanalytics/resthandler/OCSFDetectorRestApiIT.java
Implements some fixes found in end-to-end validation of added OCSF1.1 field mappings on mock Security Lake data. Fixes include:
1. Removed `[]` from newly added WAF field mappings. The static mappings can parse fields in lists without being explicitly indicated that the field is a list, so the square brackets were being treated as part of the field name itself.
2. Checking for an OCSF1.1 field mapping before checking for an OCSF1.0 field mapping. This resolves a confusion the static mappings had on how to map OCSF1.1 fields `actor.user.uid`, `actor.user.uid_alt` to ECS fields `aws.cloudtrail.user_identity.principalId` and `aws.cloudtrail.user_identity.arn`.
Previously, in OCSF1.0, the field mappings for ECS fields were:
`aws.cloudtrail.user_identity.principalId` -> `actor.user.uid` …
=> OCSF1.1 Fixes

src/main/java/org/opensearch/securityanalytics/threatIntel/model/Source.java, src/test/java/org/opensearch/securityanalytics/threatIntel/model/ThreatIntelSourceTests.java
Added catch for unexpected inputs.
=> Added catch for unexpected inputs.

.github/workflows/multi-node-test-workflow.yml
CVE details:
```
{
"VulnerabilityID": "CVE-2024-47535",
"PkgName": "io.netty:netty-common",
"PkgPath": "usr/share/opensearch/plugins/opensearch-security-analytics/security-analytics-commons-1.0.0.jar",
"PkgIdentifier": {
"PURL": "pkg:maven/io.netty/netty-common@4.1.108.Final"
},
"InstalledVersion": "4.1.108.Final",
"FixedVersion": "4.1.115",
"Status": "fixed",
"Layer": {
"Digest": "sha256:490d0de45822d74701c986814b57e4d8132164424019877b38915dadc07ae80a",
"DiffID": "sha256:1d1542b17eec3a37159135e2fce5b242073af921fcdbdd889b267c28ace4e2a4"
},
"SeveritySource": "ghsa",
"PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-47535",
"DataSource": {
"ID": "ghsa",
"Name": "GitHub Security Advisory Maven",
"URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven"
},
"Title": …
```
=> Fix CVE-2024-47535.

src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
1. Based on PR https://github.com/opensearch-project/security-analytics/pull/1457, added wait times to some tests to reduce flakiness.
https://ci.opensearch.org/ci/dbc/integ-test/2.19.0/10772/linux/x64/tar/test-results/9318/integ-test/security-analytics/with-security/opensearch-integ-test/classes/org.opensearch.securityanalytics.alerts.AlertsIT.html#testMultipleAggregationAndDocRules_alertSuccess
2. Removed some unused imports.
https://github.com/opensearch-project/security-analytics/issues/1451
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/security-analytics/blob/main/C …
=> Refactored flaky test.

build.gradle
1. Manual backport of PR https://github.com/opensearch-project/security-analytics/pull/1481
2. Added filtering to exclude conflicting dependencies from alerting jar.
=> [Backport 2.19] Updated commons jar to fix CVE-2025-24970, and CVE-2025-25193.

build.gradle
1. Manual backport of PR https://github.com/opensearch-project/security-analytics/pull/1481
1. Added filtering to exclude conflicting dependencies from alerting jar.
=> [Backport 2.x] Updated commons jar to fix CVE-2025-24970, and CVE-2025-25193.

.github/workflows/ci.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties
Update gradle 8.10.2 and support jdk23
https://github.com/opensearch-project/security-analytics/issues/1350#issuecomment-2691259392
https://github.com/opensearch-project/security-analytics/issues/1025
- ~~[ ] New functionality includes testing.~~
- ~~[ ] New functionality has been documented.~~
- ~~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~~
- ~~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~~
For more information on following Developer Certificate of Origin and signing off your commits, please …
=> Update gradle 8.10.2 and support jdk23

src/test/java/org/opensearch/securityanalytics/resthandler/CustomSchemaSourceConfigIocUploadIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/SourceConfigWithoutS3RestApiIT.java, src/test/java/org/opensearch/securityanalytics/resthandler/ThreatIntelMonitorRestApiIT.java
Addresses failures seen in 3.0.0-alpha1 integ tests: https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test/detail/integ-test/9475/pipeline/135/#step-859-log-689
While this repo is not directly deleting the security index, its delegating test cleanup to the [OpenSearchRestTestCase](https://github.com/opensearch-project/OpenSearch/blob/main/test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java) base class which has logic to cleanup all indices with this override. 
Resolves https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test/detail/integ-test/9475/pipeline/135/#step-859-log-689
For more information on following …
=> Remove overrides of preserveIndicesUponCompletion

src/main/java/org/opensearch/securityanalytics/threatIntel/iocscan/dao/BaseEntityCrudService.java
This field on BulkRequest was never set by this code. I'm not sure why it was being logged. I can only assume it was confused with the `batchSize` parameter, so I've logged that instead.
Closes https://github.com/opensearch-project/security-analytics/issues/1502
=> Remove usage of deprecated batchSize() method

build.gradle, src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java
SAP has its guava dependencies set at compileOnly level which means they are not packaged into the SAP assembly and available at runtime. 
SAP uses these deps at runtime, however, the way this works is because of the extending relationship between SAP and JS plugin where the deps of the extended plugin are available to the extending plugin at runtime.
In https://github.com/opensearch-project/job-scheduler/pull/773, guava was removed from JS which means these deps are no longer available to SAP at runtime. I'm creating this PR to change the guava deps from compileOnly to implementation to ensure they are included in the assembly and available at runtime.
For more information …
=> Switch guava deps from compileOnly to implementation

build.gradle, src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java, src/main/java/org/opensearch/securityanalytics/threatIntel/common/TIFLockService.java, src/test/java/org/opensearch/securityanalytics/correlation/CorrelationEngineRestApiIT.java, src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java, src/test/java/org/opensearch/securityanalytics/threatIntel/ThreatIntelTestCase.java, src/test/java/org/opensearch/securityanalytics/threatIntel/common/ThreatIntelLockServiceTests.java
Companion JS PR: https://github.com/opensearch-project/job-scheduler/pull/670
This PR shows how SAP can be refactored to use the instance of the LockService that is initialized in Job Scheduler's `createComponents`.
This PR is part of an effort to remove usages of `ThreadContext.stashContext` across the plugins: https://github.com/opensearch-project/opensearch-plugins/issues/238
Currently, security analytics instantiates its own instance of the LockService by passing in the Client given to analytics through `createComponents`.
As part of the effort to [Strengthen System Indices in the Plugin Ecosystem](https://github.com/opensearch-project/security/issues/4439), plugins will be restricted to only perform transport actions to their own system indices. This PR is to ensure that SAP uses the …
=> Use instance of LockService instantiated in JobScheduler through Guice

src/test/java/org/opensearch/securityanalytics/TestHelpers.java, src/test/java/org/opensearch/securityanalytics/model/WriteableTests.java, src/test/java/org/opensearch/securityanalytics/model/threatintel/ThreatIntelAlertTests.java
Many repos have a user attribute called `custom_attribute_names` that is in their system index mappings when storing a copy of the user. This field exists, but was never plumbed rendering this field as useless. 
There is a bugfix underway to fix an [issue in the alerting repo](https://github.com/opensearch-project/alerting/issues/1829) when an alerting monitor is created by a user that has DLS restrictions that have user attribute substitutions. As part of fixing the bug, the field `custom_attribute_names` will now be used and each entry in the list is expected to be in the `attrKey=attrVal` format. This PR ensures that test data that the security-analytics plugin creates conforms to this expected format.
By submitting this pull request, I confirm that my contribution is made under the …
=> Ensure that user attributes are in expected format attrKey=attrVal for testing
